# Generated by Django 5.2.6 on 2026-05-04 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('mensagem', models.TextField()),
                ('resolvido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Descricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Coletores', 'Coletores'), ('Impressoras', 'Impressoras'), ('Notebooks', 'Notebooks'), ('Routers', 'Routers')], db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases', to='estoque.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('patrimonio', models.CharField(max_length=100, unique=True)),
                ('responsavel', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('TRANSFERENCIA', 'Em Transferência'), ('MANUTENCAO', 'Manutenção'), ('SICK', 'Sick'), ('BAIXA', 'Baixa')], default='ATIVO', max_length=20)),
                ('data_aquisicao', models.DateField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipamentos/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('regional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.base')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('TRANSFERENCIA', 'Transferência'), ('STATUS', 'Mudança de Status'), ('EDICAO', 'Edição')], max_length=50)),
                ('detalhes', models.JSONField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.equipamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('gestor', 'Gestor'), ('operador', 'Operador')], max_length=10)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='estoque.empresa')),
                ('regionais', models.ManyToManyField(blank=True, related_name='perfis', to='estoque.base')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('motivo', models.TextField()),
                ('previsao_retorno', models.DateField(blank=True, null=True)),
                ('data_ocorrencia', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('equipamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sick', to='estoque.equipamento')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('EM_TRANSFERENCIA', 'Em Transferência'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('aprovado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('regional_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origens', to='estoque.base')),
                ('regional_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.base')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('atendido', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.solicitacao')),
            ],
        ),
        migrations.CreateModel(
            name='AlocacaoSolicitacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('regional_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.base')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='estoque.solicitacaoitem')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('RECEBIDO', 'Recebido')], default='PENDENTE', max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_recebimento', models.DateTimeField(blank=True, null=True)),
                ('alocacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.alocacaosolicitacaoitem')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.equipamento')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recebidas', to=settings.AUTH_USER_MODEL)),
                ('regional_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='estoque.base')),
                ('regional_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origem', to='estoque.base')),
                ('solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='estoque.solicitacao')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['status'], name='estoque_equ_status_fff69c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['regional'], name='estoque_equ_regiona_55bdc3_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['data_cadastro'], name='estoque_equ_data_ca_df5537_idx'),
        ),
    ]
