# Generated by Django 5.2.6 on 2026-02-04 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'ordering': ['produto__descricao', 'numero_serie'], 'verbose_name': 'Equipamento', 'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.AlterModelOptions(
            name='historico',
            options={'ordering': ['-data'], 'verbose_name': 'Histórico', 'verbose_name_plural': 'Históricos'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['descricao'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='sick',
            options={'ordering': ['-data_ocorrencia'], 'verbose_name': 'Registro SICK', 'verbose_name_plural': 'Registros SICK'},
        ),
        migrations.AlterModelOptions(
            name='transferencia',
            options={'ordering': ['-data_solicitacao'], 'verbose_name': 'Transferência', 'verbose_name_plural': 'Transferências'},
        ),
        migrations.RemoveField(
            model_name='historico',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='origem',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de aquisição'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_baixa',
            field=models.DateField(blank=True, null=True, verbose_name='Data de baixa'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_garantia',
            field=models.DateField(blank=True, null=True, verbose_name='Data fim da garantia'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='local_exato',
            field=models.CharField(blank=True, max_length=200, verbose_name='Local exato (sala/prateleira)'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='responsavel',
            field=models.CharField(blank=True, max_length=150, verbose_name='Responsável atual'),
        ),
        migrations.AddField(
            model_name='historico',
            name='detalhes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historico',
            name='tipo_acao',
            field=models.CharField(choices=[('CRIACAO', 'Criação'), ('ATUALIZACAO', 'Atualização'), ('TRANSFERENCIA', 'Transferência'), ('SICK', 'Marcado como SICK'), ('RECEBIMENTO', 'Recebimento'), ('MANUTENCAO', 'Enviado para manutenção'), ('BAIXA', 'Baixa do equipamento'), ('RESOLUCAO_SICK', 'Resolução de SICK')], default='CRIACAO', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sick',
            name='categoria',
            field=models.CharField(choices=[('DEFEITO', 'Defeito técnico'), ('DANIFICADO', 'Danificado fisicamente'), ('OBSOLETO', 'Obsoleto'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50),
        ),
        migrations.AddField(
            model_name='sick',
            name='data_resolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sick',
            name='previsao_retorno',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de retorno'),
        ),
        migrations.AddField(
            model_name='sick',
            name='resolvido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sick_resolvidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='local_destino',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='local_origem',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='motivo',
            field=models.TextField(blank=True, verbose_name='Motivo da transferência'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='patrimonio',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='regional',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('SICK', 'Sick'), ('TRANSFERENCIA', 'Em transferência'), ('MANUTENCAO', 'Em manutenção'), ('BAIXA', 'Baixa')], db_index=True, default='ATIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='historico',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='estoque.equipamento'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='regional_destino',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='regional_origem',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['status', 'regional'], name='estoque_equ_status_1d4004_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['regional', 'status'], name='estoque_equ_regiona_9fd5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['data_cadastro'], name='estoque_equ_data_ca_df5537_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['data_atualizacao'], name='estoque_equ_data_at_845049_idx'),
        ),
        migrations.AddIndex(
            model_name='historico',
            index=models.Index(fields=['equipamento', '-data'], name='estoque_his_equipam_dfed93_idx'),
        ),
        migrations.AddIndex(
            model_name='historico',
            index=models.Index(fields=['tipo_acao', 'data'], name='estoque_his_tipo_ac_a80408_idx'),
        ),
        migrations.AddIndex(
            model_name='sick',
            index=models.Index(fields=['equipamento', '-data_ocorrencia'], name='estoque_sic_equipam_dab0e2_idx'),
        ),
        migrations.AddIndex(
            model_name='sick',
            index=models.Index(fields=['categoria', 'data_ocorrencia'], name='estoque_sic_categor_382991_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['status', 'data_solicitacao'], name='estoque_tra_status_13da24_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['equipamento', 'data_solicitacao'], name='estoque_tra_equipam_42a369_idx'),
        ),
    ]
