# Generated by Django 5.2.6 on 2026-05-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sick',
            name='observacao_resolucao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sick',
            name='status_final',
            field=models.CharField(blank=True, choices=[('ATIVO', 'Ativo'), ('SICK', 'SICK'), ('MANUTENCAO', 'Manutenção'), ('SUCATA', 'Sucata'), ('INATIVO', 'Inativo')], max_length=20, null=True),
        ),
    ]
