# Generated by Django 5.2.6 on 2026-02-19 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_equipamento_options_alter_historico_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='equipamento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historico',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sick',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transferencia',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='equipamento',
            name='estoque_equ_status_1d4004_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipamento',
            name='estoque_equ_regiona_9fd5ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipamento',
            name='estoque_equ_data_ca_df5537_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipamento',
            name='estoque_equ_data_at_845049_idx',
        ),
        migrations.RemoveIndex(
            model_name='historico',
            name='estoque_his_equipam_dfed93_idx',
        ),
        migrations.RemoveIndex(
            model_name='historico',
            name='estoque_his_tipo_ac_a80408_idx',
        ),
        migrations.RemoveIndex(
            model_name='sick',
            name='estoque_sic_equipam_dab0e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='sick',
            name='estoque_sic_categor_382991_idx',
        ),
        migrations.RemoveIndex(
            model_name='transferencia',
            name='estoque_tra_status_13da24_idx',
        ),
        migrations.RemoveIndex(
            model_name='transferencia',
            name='estoque_tra_equipam_42a369_idx',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='data_baixa',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='local_origem',
        ),
        migrations.AlterField(
            model_name='descricao',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_garantia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='equipamentos/'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='local_exato',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='patrimonio',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('TRANSFERENCIA', 'Em Transferência'), ('MANUTENCAO', 'Manutenção'), ('SICK', 'Sick'), ('BAIXA', 'Baixa')], default='ATIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='historico',
            name='detalhes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historico',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.equipamento'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='tipo_acao',
            field=models.CharField(choices=[('CRIACAO', 'Criação'), ('TRANSFERENCIA', 'Transferência'), ('STATUS', 'Mudança de Status'), ('EDICAO', 'Edição')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fabricante',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sick',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sick',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.equipamento'),
        ),
        migrations.AlterField(
            model_name='sick',
            name='previsao_retorno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sick',
            name='resolvido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.equipamento'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='local_destino',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.base'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='regional_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destino', to='estoque.base'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='regional_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origem', to='estoque.base'),
        ),
    ]
