# Generated by Django 5.2.6 on 2026-05-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_sick_observacao_resolucao_sick_status_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sick',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
