# Generated by Django 5.2.6 on 2026-05-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_sick_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='idioma',
            field=models.CharField(choices=[('pt-br', 'Português'), ('es', 'Español')], default='pt-br', max_length=10),
        ),
    ]
