# Generated by Django 5.2.6 on 2026-02-19 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_base_alter_equipamento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='data_garantia',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='local_exato',
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_aquisicao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.base')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
