# Generated by Django 5.2.6 on 2026-03-19 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_remove_equipamento_data_garantia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('mensagem', models.TextField()),
                ('resolvido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='regional',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='regionais',
            field=models.ManyToManyField(to='estoque.base'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('gestor', 'Gestor'), ('operador', 'Operador')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sick',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='protocolo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historico',
            name='data',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sick',
            name='data_ocorrencia',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sick',
            name='equipamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estoque.equipamento'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='status',
            field=models.CharField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['status'], name='estoque_equ_status_fff69c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['regional'], name='estoque_equ_regiona_55bdc3_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['data_cadastro'], name='estoque_equ_data_ca_df5537_idx'),
        ),
        migrations.AddField(
            model_name='base',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.empresa'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.empresa'),
        ),
    ]
