# Generated by Django 5.2.6 on 2026-05-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_gruporegional_base_grupo_regional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_TRANSITO', 'Em trânsito'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20),
        ),
    ]
