# Generated by Django 5.2.6 on 2026-03-30 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alerta_empresa_remove_perfil_regional_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.empresa'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('gestor', 'Gestor'), ('operador', 'Operador')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sick',
            name='equipamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sick', to='estoque.equipamento'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='protocolo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('EM_TRANSFERENCIA', 'Em Transferência'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=20)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto')),
                ('regional_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_origem', to='estoque.base')),
                ('regional_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.base')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transferencia',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.solicitacao'),
        ),
        migrations.AddConstraint(
            model_name='transferencia',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDENTE')), fields=('equipamento',), name='unique_transferencia_pendente_por_equipamento'),
        ),
    ]
