# Generated by Django 5.2.6 on 2026-04-07 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_alter_base_empresa_alter_equipamento_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='regionais',
        ),
        migrations.AddField(
            model_name='perfil',
            name='regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis', to='estoque.base'),
        ),
        migrations.AlterField(
            model_name='base',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases', to='estoque.empresa'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='estoque.empresa'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('gestor', 'Gestor'), ('operador', 'Operador')], max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
