# Generated by Django 5.2.6 on 2026-04-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_remove_perfil_regionais_perfil_regional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Coletores', 'Coletores'), ('Impressoras', 'Impressoras'), ('Notebooks', 'Notebooks'), ('Routers', 'Routers')], default='Coletores', max_length=50),
            preserve_default=False,
        ),
    ]
