# Generated by Django 5.2.6 on 2026-05-15 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_corrigir_notificacao_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sick',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sicks', to='estoque.equipamento'),
        ),
    ]
