# Generated by Django 5.2.6 on 2026-04-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_produto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='regional',
        ),
        migrations.AddField(
            model_name='perfil',
            name='regionais',
            field=models.ManyToManyField(blank=True, related_name='perfis_multiplos', to='estoque.base'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Coletores', 'Coletores'), ('Impressoras', 'Impressoras'), ('Notebooks', 'Notebooks'), ('Routers', 'Routers')], db_index=True, max_length=50),
        ),
    ]
