# Generated by Django 5.2.6 on 2026-05-15 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_alter_sick_equipamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('INFO', 'Informativo'), ('URGENTE', 'Urgente'), ('MANUTENCAO', 'Manutenção'), ('OPERACIONAL', 'Operacional')], default='INFO', max_length=20)),
                ('enviar_para_todos', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.empresa')),
                ('usuarios', models.ManyToManyField(blank=True, related_name='comunicados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComunicadoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='comunicados/')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='estoque.comunicado')),
            ],
        ),
        migrations.CreateModel(
            name='ComunicadoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lido_em', models.DateTimeField(auto_now_add=True)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.comunicado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MensagemArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='mensagens/')),
                ('nome_original', models.CharField(max_length=255)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='estoque.mensagem')),
            ],
        ),
        migrations.CreateModel(
            name='MensagemDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lido', models.BooleanField(default=False)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='estoque.mensagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
