# Generated by Django 5.2.6 on 2026-04-15 21:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_remove_perfil_regional_perfil_regionais_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transferencia',
            name='unique_transferencia_pendente_por_equipamento',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='data_finalizacao',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='solicitante',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='data_solicitacao',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='local_destino',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='protocolo',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='motivo',
            field=models.TextField(default='Sem Motivo Informado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferencia',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='regionais',
            field=models.ManyToManyField(blank=True, related_name='perfis', to='estoque.base'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='aprovado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='regional_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origens', to='estoque.base'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='regional_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.base'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.equipamento'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='recebido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='regional_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='estoque.base'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='regional_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origem', to='estoque.base'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.solicitacao'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='solicitado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='status',
            field=models.CharField(default='PENDENTE', max_length=20),
        ),
    ]
