# Generated by Django 5.2.6 on 2026-05-18 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_comunicado_expira_em_comunicado_permitir_limpar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('RESERVADO_TRANSFERENCIA', 'Reservado para Transferência'), ('EM_TRANSITO', 'Em Trânsito'), ('MANUTENCAO', 'Manutenção'), ('SICK', 'Sick'), ('BAIXA', 'Baixa')], default='ATIVO', max_length=40),
        ),
        migrations.AlterField(
            model_name='sick',
            name='status_final',
            field=models.CharField(blank=True, choices=[('ATIVO', 'Ativo'), ('SICK', 'SICK'), ('MANUTENCAO', 'Manutenção'), ('SUCATA', 'Sucata'), ('INATIVO', 'Inativo')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('EM_TRANSFERENCIA', 'Em Transferência'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=40),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_TRANSITO', 'Em trânsito'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=40),
        ),
        migrations.CreateModel(
            name='AlocacaoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selecionado_em', models.DateTimeField(auto_now_add=True)),
                ('alocacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_fisicos', to='estoque.alocacaosolicitacaoitem')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.equipamento')),
            ],
            options={
                'unique_together': {('alocacao', 'equipamento')},
            },
        ),
        migrations.AddField(
            model_name='alocacaosolicitacaoitem',
            name='equipamentos',
            field=models.ManyToManyField(blank=True, through='estoque.AlocacaoEquipamento', to='estoque.equipamento'),
        ),
    ]
