# Generated by Django 5.2.6 on 2026-04-22 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_remove_transferencia_unique_transferencia_pendente_por_equipamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sick',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='estoque.solicitacao'),
        ),
    ]
