# Generated by Django 5.2.6 on 2026-04-22 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_sick_descricao_alter_transferencia_solicitacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencia',
            name='solicitacao',
        ),
        migrations.CreateModel(
            name='AlocacaoSolicitacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('regional_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.base')),
            ],
        ),
        migrations.AddField(
            model_name='transferencia',
            name='alocacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.alocacaosolicitacaoitem'),
        ),
        migrations.CreateModel(
            name='SolicitacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('atendido', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.solicitacao')),
            ],
        ),
        migrations.AddField(
            model_name='alocacaosolicitacaoitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='estoque.solicitacaoitem'),
        ),
    ]
