# Generated by Django 5.2.6 on 2026-04-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_remove_transferencia_solicitacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='quantidade',
        ),
    ]
