# Generated by Django 5.2.6 on 2026-05-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_alter_equipamento_status_alter_sick_status_final_and_more'),
        ('estoque', '0012_fix_alocacao_missing_table'),
    ]

    operations = [
    ]
