# Generated by Django 5.2.6 on 2026-05-18 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_merge_20260518_1616'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacaosolicitacaoitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alocacaosolicitacaoitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='estoque.solicitacaoitem'),
        ),
        migrations.AlterField(
            model_name='alocacaosolicitacaoitem',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelTable(
            name='alocacaosolicitacaoitem',
            table=None,
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('quantidade', models.PositiveIntegerField()),
                ('status', models.CharField(default='ABERTO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('regional_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_destino', to='estoque.base')),
                ('regional_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_origem', to='estoque.base')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.solicitacao')),
            ],
        ),
    ]
