# Generated by Django 5.2.6 on 2026-04-23 17:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_remove_solicitacao_produto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='regional_origem',
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='regional_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='estoque.base'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('EM_TRANSFERENCIA', 'Em Transferência'), ('FINALIZADO', 'Finalizado')], db_index=True, default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitacaoitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='alocacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias', to='estoque.alocacaosolicitacaoitem'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.equipamento'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('RECEBIDO', 'Recebido')], db_index=True, default='PENDENTE', max_length=20),
        ),
    ]
