# Generated by Django 5.2.6 on 2026-05-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_alter_alocacaosolicitacaoitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='tipo_acao',
            field=models.CharField(choices=[('CRIACAO', 'Criação'), ('TRANSFERENCIA', 'Transferência'), ('STATUS', 'SICK'), ('EDICAO', 'Edição')], max_length=50),
        ),
    ]
