# Generated by Django 5.2.6 on 2026-04-23 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_remove_solicitacao_regional_origem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoitem',
            name='produto',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='regional_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origens', to='estoque.base'),
        ),
        migrations.AddField(
            model_name='solicitacaoitem',
            name='categoria',
            field=models.CharField(choices=[('Coletores', 'Coletores'), ('Impressoras', 'Impressoras'), ('Notebooks', 'Notebooks'), ('Routers', 'Routers')], db_index=True, default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='aprovado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='regional_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.base'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('EM_TRANSFERENCIA', 'Em Transferência'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='alocacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.alocacaosolicitacaoitem'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.equipamento'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='status',
            field=models.CharField(default='PENDENTE', max_length=20),
        ),
    ]
