# Generated by Django 5.2.6 on 2026-05-20 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0015_alter_historico_tipo_acao'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferencia',
            name='protocolo',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferencia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
