# Generated by Django 5.2.6 on 2026-04-26 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0015_remove_solicitacaoitem_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.equipamento'),
        ),
    ]
