# Generated by Django 5.2.6 on 2026-04-26 05:30

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0016_alter_transferencia_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='alocacao',
            field=models.ForeignKey(
                to='estoque.alocacaosolicitacaoitem',
                on_delete=models.SET_NULL,
                null=True,
                blank=True,
            ),
        ),
    ]
