# Generated by Django 5.2.6 on 2026-05-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0017_fix_alocacao_transferencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencia',
            name='alocacao',
        ),
        migrations.AddField(
            model_name='transferencia',
            name='alocacao_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto'),
        ),
    ]
