# Generated by Django 5.2.6 on 2026-05-04 21:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0017_fix_alocacao_transferencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='recebido_por',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferencia',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='data_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='regional_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='estoque.base'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='regional_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origem', to='estoque.base'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='solicitado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='status',
            field=models.CharField(default='RASCUNHO', max_length=20),
        ),
        migrations.AlterModelTable(
            name='solicitacaoitem',
            table='estoque_itemsolicitacao',
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SOLICITACAO', 'Solicitação'), ('TRANSFERENCIA', 'Transferência')], max_length=20)),
                ('evento', models.CharField(choices=[('CRIADA', 'Criada'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('EM_TRANSFERENCIA', 'Em transferência'), ('RECEBIDA', 'Recebida')], max_length=30)),
                ('mensagem', models.CharField(max_length=255)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferenciaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('equipamentos', models.ManyToManyField(blank=True, to='estoque.equipamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.transferencia')),
            ],
        ),
    ]
