# Generated by Django 5.2.6 on 2026-05-25 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0017_alocacaosolicitacaoitem_produto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=20, unique=True)),
                ('motivo', models.TextField()),
                ('data_emprestimo', models.DateField()),
                ('data_prevista_devolucao', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROVADO', 'Aprovado'), ('EM_TRANSITO', 'Em trânsito'), ('EMPRESTADO', 'Emprestado'), ('DEVOLVIDO', 'Devolvido'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20)),
                ('confirmado_recebimento', models.BooleanField(default=False)),
                ('confirmado_devolucao', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_aprovados', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.gruporegional')),
                ('regional_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_entrada', to='estoque.base')),
                ('regional_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_saida', to='estoque.base')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('DEVOLVIDO', 'Devolvido'), ('DIVERGENCIA', 'Divergência')], default='PENDENTE', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.emprestimo')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.equipamento')),
            ],
        ),
    ]
