# Generated by Django 5.2.6 on 2026-05-04 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0018_remove_transferencia_alocacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='estoque.solicitacao'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='alocacao_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.equipamento'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('RECEBIDO', 'Recebido')], default='PENDENTE', max_length=20),
        ),
    ]
