# Generated by Django 5.2.6 on 2026-05-05 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0018_remove_solicitacao_data_criacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PedidoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='ABERTO', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='notificacao',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.solicitacao'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='transferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.transferencia'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.equipamento'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='status',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('RECEBIDO', 'Recebido'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='notificacao',
            constraint=models.UniqueConstraint(fields=('usuario', 'tipo', 'evento', 'transferencia', 'solicitacao'), name='unique_notificacao_evento_transferencia'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto'),
        ),
        migrations.AddField(
            model_name='pedidotransferencia',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidotransferencia',
            name='regional_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_destino', to='estoque.base'),
        ),
        migrations.AddField(
            model_name='pedidotransferencia',
            name='regional_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_origem', to='estoque.base'),
        ),
        migrations.AddField(
            model_name='pedidotransferencia',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.solicitacao'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.pedidotransferencia'),
        ),
    ]
