# Generated by Django 5.2.6 on 2026-05-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0018_emprestimo_itememprestimo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gruporegional',
            options={'ordering': ['nome'], 'verbose_name': 'Grupo Regional', 'verbose_name_plural': 'Grupos Regionais'},
        ),
        migrations.AddField(
            model_name='itememprestimo',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
