# Generated by Django 5.2.6 on 2026-05-27 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0019_alter_gruporegional_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicadoleitura',
            name='comunicado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='estoque.comunicado'),
        ),
    ]
