# Generated by Django 5.2.6 on 2026-05-27 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0020_alter_comunicadoleitura_comunicado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='data_recusa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='motivo_recusa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='recusado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recusas_solicitacao', to=settings.AUTH_USER_MODEL),
        ),
    ]
