# Generated by Django 5.2.6 on 2026-05-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0019_pedidoitem_pedidotransferencia_and_more'),
        ('estoque', '0020_create_notificacao_fix'),
    ]

    operations = [
    ]
