# Generated by Django 5.2.6 on 2026-05-05 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0021_merge_20260505_1412'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='evento',
            field=models.CharField(choices=[('CRIADA', 'Criada'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('EM_TRANSFERENCIA', 'Em transferência'), ('RECEBIDA', 'Recebida')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('SOLICITACAO', 'Solicitação'), ('TRANSFERENCIA', 'Transferência')], max_length=20),
        ),
    ]
