# Generated by Django 5.2.6 on 2026-06-01 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0021_solicitacao_data_recusa_solicitacao_motivo_recusa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivergenciaTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_recebida', models.CharField(blank=True, max_length=100)),
                ('patrimonio_recebido', models.CharField(blank=True, max_length=100)),
                ('observacao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvida', models.BooleanField(default=False)),
                ('equipamento_enviado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divergencias_enviadas', to='estoque.equipamento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.transferenciaitem')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.transferencia')),
            ],
        ),
    ]
