# Generated by Django 5.2.6 on 2026-06-01 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0022_divergenciatransferencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendenciaTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIVERGENCIA', 'Divergência'), ('NAO_RECEBIDO', 'Não recebido')], max_length=30)),
                ('patrimonio_esperado', models.CharField(blank=True, max_length=100)),
                ('serie_esperada', models.CharField(blank=True, max_length=150)),
                ('patrimonio_recebido', models.CharField(blank=True, max_length=100)),
                ('serie_recebida', models.CharField(blank=True, max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em análise'), ('RESOLVIDA', 'Resolvida')], default='ABERTA', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='estoque.transferenciaitem')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='estoque.transferencia')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
