# Generated by Django 5.2.6 on 2026-06-01 19:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0023_pendenciatransferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendenciatransferencia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendenciatransferencia',
            name='equipamento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='estoque.equipamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendenciatransferencia',
            name='motivo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
