# Generated by Django 5.2.6 on 2026-06-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0024_pendenciatransferencia_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_RECEBIMENTO', 'Aguardando recebimento'), ('EMPRESTADO', 'Emprestado'), ('AGUARDANDO_CONFIRMACAO_DEVOLUCAO', 'Aguardando confirmação devolução'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=35),
        ),
        migrations.AlterField(
            model_name='itememprestimo',
            name='status',
            field=models.CharField(choices=[('RESERVADO', 'Reservado'), ('ENVIADO', 'Enviado'), ('RECEBIDO', 'Recebido'), ('DEVOLVIDO', 'Devolvido'), ('DIVERGENCIA', 'Divergência')], default='PENDENTE', max_length=20),
        ),
    ]
