# Generated by Django 5.2.6 on 2026-06-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0025_alter_emprestimo_status_alter_itememprestimo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('RESERVADO_TRANSFERENCIA', 'Reservado para Transferência'), ('EM_TRANSITO', 'Em Trânsito'), ('MANUTENCAO', 'Manutenção'), ('SICK', 'Sick'), ('EM_USO', 'Em Uso'), ('BAIXA', 'Baixa')], default='ATIVO', max_length=40),
        ),
    ]
