# Generated by Codex on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0026_alter_equipamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefone_alternativo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
