# Generated by Codex on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0027_perfil_telefones'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bases_checklist',
            field=models.ManyToManyField(blank=True, related_name='perfis_checklist', to='estoque.base'),
        ),
    ]
