# Generated by Django 5.2.6 on 2026-07-17 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def classificar_sicks_existentes(apps, schema_editor):
    Sick = apps.get_model('estoque', 'Sick')
    Sick.objects.filter(
        models.Q(ativo=False) |
        models.Q(data_resolucao__isnull=False) |
        models.Q(status_final__in=['ATIVO', 'INATIVO', 'SUCATA'])
    ).update(etapa='FINALIZADO')
    Sick.objects.filter(ativo=True, status_final='MANUTENCAO').update(
        etapa='EM_MANUTENCAO'
    )


def reverter_classificacao_sicks(apps, schema_editor):
    apps.get_model('estoque', 'Sick').objects.update(etapa='IDENTIFICADO')


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0029_alter_equipamento_status_inativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sick',
            options={'permissions': [('enviar_equipamento_manutencao', 'Pode enviar equipamento para manutenção'), ('receber_equipamento_manutencao', 'Pode confirmar recebimento na manutenção'), ('avaliar_equipamento_sick', 'Pode avaliar equipamento SICK'), ('iniciar_manutencao_equipamento', 'Pode iniciar manutenção'), ('concluir_manutencao_equipamento', 'Pode concluir manutenção'), ('confirmar_retorno_equipamento', 'Pode confirmar retorno do equipamento'), ('corrigir_fluxo_sick', 'Pode corrigir etapas do fluxo SICK')]},
        ),
        migrations.AddField(
            model_name='comunicado',
            name='dados',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='finalidade',
            field=models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('ADMINISTRATIVO', 'Administrativo')], db_index=True, default='OPERACIONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='sick',
            name='apto_retorno',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sick',
            name='avaliacao_iniciada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sick',
            name='avaliacao_iniciada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sicks_avaliados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sick',
            name='causa_identificada',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sick',
            name='destino_manutencao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sick',
            name='diagnostico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sick',
            name='enviado_manutencao_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sick',
            name='enviado_manutencao_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sicks_enviados_manutencao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sick',
            name='etapa',
            field=models.CharField(choices=[('IDENTIFICADO', 'Identificado na base'), ('EM_TRANSITO', 'Em trânsito para manutenção'), ('RECEBIDO', 'Recebido pela manutenção'), ('EM_AVALIACAO', 'Em avaliação técnica'), ('EM_MANUTENCAO', 'Em manutenção'), ('AGUARDANDO_RETORNO', 'Aguardando retorno para a base'), ('FINALIZADO', 'Finalizado')], db_index=True, default='IDENTIFICADO', max_length=30),
        ),
        migrations.AddField(
            model_name='sick',
            name='manutencao_concluida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sick',
            name='manutencao_concluida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sicks_manutencao_concluida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sick',
            name='manutencao_iniciada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sick',
            name='manutencao_iniciada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sicks_manutencao_iniciada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sick',
            name='observacao_tecnica',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sick',
            name='protocolo_envio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sick',
            name='recebido_manutencao_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sick',
            name='recebido_manutencao_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sicks_recebidos_manutencao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sick',
            name='resultado_manutencao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sick',
            name='retorno_confirmado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sick',
            name='retorno_confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sicks_retorno_confirmado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sick',
            name='solucao_aplicada',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sick',
            name='transportadora_ou_portador',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(
            classificar_sicks_existentes,
            reverter_classificacao_sicks,
        ),
        migrations.AlterField(
            model_name='historico',
            name='tipo_acao',
            field=models.CharField(choices=[('CRIACAO', 'Criação'), ('TRANSFERENCIA', 'Transferência'), ('STATUS', 'SICK'), ('EDICAO', 'Edição'), ('SICK', 'Marcado como SICK'), ('SICK_ATUALIZADO', 'SICK atualizado'), ('SICK_ENVIO_MANUTENCAO', 'Enviado para manutenção'), ('SICK_RECEBIMENTO_MANUTENCAO', 'Recebido pela manutenção'), ('SICK_AVALIACAO', 'Avaliação técnica iniciada'), ('MANUTENCAO_INICIADA', 'Manutenção iniciada'), ('MANUTENCAO_ATUALIZADA', 'Manutenção atualizada'), ('MANUTENCAO_CONCLUIDA', 'Manutenção concluída'), ('SICK_AGUARDANDO_RETORNO', 'Aguardando retorno'), ('SICK_RETORNO_CONFIRMADO', 'Retorno confirmado'), ('RESOLUCAO_SICK', 'SICK finalizado'), ('SICK_REABERTO', 'SICK reaberto')], max_length=50),
        ),
    ]
