# Generated by Django 5.2.6 on 2026-08-04 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0030_alter_sick_options_comunicado_dados_comunicado_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='whatsapp_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='whatsapp_consentimento_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='whatsapp_consentimento_origem',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='whatsapp_numero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='aprovacao_admin_dispensada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='motivo_dispensa_aprovacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='origem_fluxo',
            field=models.CharField(choices=[('COMUM', 'Transferência comum'), ('SOLICITACAO', 'Solicitação'), ('AUDITORIA_DIVERGENCIA', 'Auditoria e divergência'), ('DEVOLUCAO_EMPRESTIMO', 'Devolução de empréstimo')], db_index=True, default='COMUM', max_length=30),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_RECEBIMENTO', 'Aguardando recebimento'), ('EMPRESTADO', 'Emprestado'), ('AGUARDANDO_CONFIRMACAO_DEVOLUCAO', 'Aguardando confirmação da devolução'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_RECEBIMENTO', max_length=35),
        ),
        migrations.AlterField(
            model_name='historico',
            name='tipo_acao',
            field=models.CharField(choices=[('CRIACAO', 'Criação'), ('TRANSFERENCIA', 'Transferência'), ('STATUS', 'SICK'), ('EDICAO', 'Edição'), ('SICK', 'Marcado como SICK'), ('SICK_ATUALIZADO', 'SICK atualizado'), ('SICK_ENVIO_MANUTENCAO', 'Enviado para manutenção'), ('SICK_RECEBIMENTO_MANUTENCAO', 'Recebido pela manutenção'), ('SICK_AVALIACAO', 'Avaliação técnica iniciada'), ('MANUTENCAO_INICIADA', 'Manutenção iniciada'), ('MANUTENCAO_ATUALIZADA', 'Manutenção atualizada'), ('MANUTENCAO_CONCLUIDA', 'Manutenção concluída'), ('SICK_AGUARDANDO_RETORNO', 'Aguardando retorno'), ('SICK_RETORNO_CONFIRMADO', 'Retorno confirmado'), ('RESOLUCAO_SICK', 'SICK finalizado'), ('SICK_REABERTO', 'SICK reaberto'), ('AUDITORIA_LOCALIZADO', 'Localizado em auditoria'), ('AUDITORIA_DIVERGENCIA', 'Divergência de auditoria'), ('AUDITORIA_BASE_ATUALIZADA', 'Base atualizada por auditoria'), ('AUDITORIA_TRANSFERENCIA', 'Transferência criada por auditoria'), ('AUDITORIA_REGULARIZADA', 'Regularizado por auditoria')], max_length=50),
        ),
        migrations.AlterField(
            model_name='itememprestimo',
            name='status',
            field=models.CharField(choices=[('RESERVADO', 'Reservado'), ('ENVIADO', 'Enviado'), ('RECEBIDO', 'Recebido'), ('DEVOLVIDO', 'Devolvido'), ('DIVERGENCIA', 'Divergência')], default='RESERVADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='idioma',
            field=models.CharField(choices=[('pt-br', 'Português'), ('es', 'Español'), ('en', 'English')], default='pt-br', max_length=10),
        ),
        migrations.CreateModel(
            name='DeclaracaoCorreios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacao', models.CharField(choices=[('TRANSFERENCIA', 'Transferência'), ('EMPRESTIMO', 'Empréstimo')], db_index=True, max_length=20)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EMITIDA', 'Emitida'), ('SUBSTITUIDA', 'Substituída'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20)),
                ('remetente', models.JSONField(default=dict)),
                ('destinatario', models.JSONField(default=dict)),
                ('resumo_operacao', models.JSONField(default=dict)),
                ('quantidade_volumes', models.PositiveIntegerField(default=1)),
                ('valor_total_declarado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('peso_total_kg', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, upload_to='declaracoes_correios/%Y/%m/')),
                ('hash_arquivo', models.CharField(blank=True, max_length=64)),
                ('gerada_em', models.DateTimeField(auto_now_add=True)),
                ('emprestimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declaracoes_correios', to='estoque.emprestimo')),
                ('gerada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declaracoes_correios_geradas', to=settings.AUTH_USER_MODEL)),
                ('substituida_por', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substitui', to='estoque.declaracaocorreios')),
                ('transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declaracoes_correios', to='estoque.transferencia')),
            ],
        ),
        migrations.CreateModel(
            name='DeclaracaoCorreiosItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('patrimonio', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=150)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('declaracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.declaracaocorreios')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.equipamento')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EnderecoPostalBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_destinatario', models.CharField(blank=True, max_length=150)),
                ('logradouro', models.CharField(max_length=180)),
                ('numero', models.CharField(max_length=30)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('responsavel', models.CharField(blank=True, max_length=150)),
                ('documento', models.CharField(blank=True, max_length=30)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_postal', to='estoque.base')),
            ],
        ),
        migrations.CreateModel(
            name='ComunicadoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('SISTEMA', 'Sistema'), ('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('ENVIADA', 'Enviada'), ('ENTREGUE', 'Entregue'), ('LIDA', 'Lida'), ('FALHA', 'Falha'), ('CANCELADA', 'Cancelada'), ('IGNORADA', 'Ignorada')], db_index=True, default='PENDENTE', max_length=20)),
                ('destino', models.CharField(max_length=180)),
                ('provedor', models.CharField(blank=True, max_length=50)),
                ('template_codigo', models.CharField(blank=True, max_length=100)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('proxima_tentativa_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('processada_em', models.DateTimeField(blank=True, null=True)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='estoque.comunicado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_comunicados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['canal', 'status', 'proxima_tentativa_em'], name='estoque_com_canal_91c78e_idx')],
                'constraints': [models.UniqueConstraint(fields=('comunicado', 'usuario', 'canal'), name='uq_comunicado_usuario_canal')],
            },
        ),
        migrations.AddConstraint(
            model_name='declaracaocorreios',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('emprestimo__isnull', True), ('transferencia__isnull', False)), models.Q(('emprestimo__isnull', False), ('transferencia__isnull', True)), _connector='OR'), name='ck_declaracao_exatamente_uma_operacao'),
        ),
        migrations.AddConstraint(
            model_name='declaracaocorreios',
            constraint=models.UniqueConstraint(condition=models.Q(('transferencia__isnull', False)), fields=('transferencia', 'versao'), name='uq_declaracao_transferencia_versao'),
        ),
        migrations.AddConstraint(
            model_name='declaracaocorreios',
            constraint=models.UniqueConstraint(condition=models.Q(('emprestimo__isnull', False)), fields=('emprestimo', 'versao'), name='uq_declaracao_emprestimo_versao'),
        ),
    ]
