# Generated by Django 5.2.6 on 2026-08-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0031_perfil_whatsapp_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('RESERVADO_TRANSFERENCIA', 'Reservado para Transferencia'), ('EM_TRANSITO', 'Em Transito'), ('MANUTENCAO', 'Manutencao'), ('SICK', 'Sick'), ('EM_USO', 'Em Uso'), ('EMPRESTADO', 'Emprestado'), ('BAIXA', 'Baixa'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=40),
        ),
        migrations.AlterField(
            model_name='itememprestimo',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
