# Generated by Django 5.2.6 on 2026-08-11 17:26

from django.db import migrations, models


def criar_grupos_e_preservar_acessos(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('auth', 'User')

    nomes = {
        'restrito': 'COMPRAS_RESTRITO_NOVAS_FUNCIONALIDADES',
        'sick_gerenciar': 'SICK_GERENCIAR',
        'sick_manutencao': 'SICK_MANUTENCAO',
        'comunicados': 'COMUNICADOS_EDITOR',
    }
    grupos = {
        chave: Group.objects.get_or_create(name=nome)[0]
        for chave, nome in nomes.items()
    }

    # Estes usernames aparecem somente no backfill de compatibilidade. Depois
    # da migration, toda autorização é decidida exclusivamente por grupo.
    jose = User.objects.filter(username='jose.barboza').first()
    if jose:
        jose.groups.add(
            grupos['restrito'],
            grupos['sick_gerenciar'],
            grupos['comunicados'],
        )

    rafael = User.objects.filter(username='rafael.ribeiro').first()
    if rafael:
        rafael.groups.add(
            grupos['sick_gerenciar'],
            grupos['sick_manutencao'],
            grupos['comunicados'],
        )


def reverter_grupos_criados(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=[
        'COMPRAS_RESTRITO_NOVAS_FUNCIONALIDADES',
        'SICK_GERENCIAR',
        'SICK_MANUTENCAO',
        'COMUNICADOS_EDITOR',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0033_rastreio_e_destino_sick'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bases_escopo_compras',
            field=models.ManyToManyField(blank=True, related_name='perfis_compras', to='estoque.base'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='empresas_escopo_compras',
            field=models.ManyToManyField(blank=True, related_name='perfis_compras', to='estoque.empresa'),
        ),
        migrations.RunPython(criar_grupos_e_preservar_acessos, reverter_grupos_criados),
    ]
