# Generated by Django 5.2.6 on 2026-08-11 18:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0034_perfil_bases_escopo_compras_and_more'),
        ('insumos', '0027_alter_movimentacaoinsumo_options_saldoinsumobase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='condicao_valor',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('USADO', 'Usado'), ('RECONDICIONADO', 'Recondicionado')], default='NOVO', max_length=20),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='custo_aquisicao',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='documento_compra',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos_fornecidos', to='insumos.fornecedorinsumo'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='garantia_ate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='origem_valor',
            field=models.CharField(choices=[('DOCUMENTO_COMPRA', 'Documento de compra'), ('INFORMADO_COMPRAS', 'Informado por Compras'), ('ESTIMATIVA_MERCADO', 'Estimativa de mercado'), ('LEGADO_SEM_DOCUMENTO', 'Legado sem documento'), ('SEM_PRECO_VALIDADO', 'Sem preço validado')], db_index=True, default='SEM_PRECO_VALIDADO', max_length=30),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='preco_referencia',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='valor_validado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='valor_validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos_valor_validado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produto',
            name='especificacoes_tecnicas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='produto',
            name='nome_resumido',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_embalagem',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='produto',
            name='sku_fabricante',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='subcategoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(default='UN', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_aquisicao',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
