# Generated by Django 5.2.6 on 2026-08-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0037_whatsapp_consentimento_e_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Sistema', 'Sistema'), ('Coletores', 'Coletores'), ('Notebooks', 'Notebooks'), ('Impressoras', 'Impressoras'), ('Routers', 'Routers')], db_index=True, max_length=50),
        ),
    ]
