# Generated by Django 5.2.6 on 2026-08-20 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0038_alter_produto_categoria'),
        ('insumos', '0032_alter_checklistdiario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'permissions': [('visualizar_equipamentos', 'Pode visualizar equipamentos'), ('cadastrar_equipamentos', 'Pode cadastrar equipamentos'), ('editar_equipamentos', 'Pode editar equipamentos'), ('baixar_equipamentos', 'Pode baixar equipamentos'), ('transferir_equipamentos', 'Pode transferir equipamentos'), ('visualizar_historico_equipamentos', 'Pode visualizar histórico de equipamentos'), ('gerenciar_sick_equipamentos', 'Pode gerenciar SICK de equipamentos')]},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': [('visualizar_usuarios', 'Pode visualizar usuários'), ('cadastrar_usuarios', 'Pode cadastrar usuários'), ('editar_usuarios', 'Pode editar usuários'), ('alterar_permissoes_usuario', 'Pode alterar permissões de usuários'), ('inativar_usuario', 'Pode inativar usuários'), ('reativar_usuario', 'Pode reativar usuários'), ('excluir_usuario', 'Pode excluir usuários')]},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'permissions': [('visualizar_preco_produto', 'Pode visualizar preços de produtos'), ('definir_preco_produto', 'Pode definir preço inicial de produtos'), ('alterar_preco_produto', 'Pode alterar preços de produtos'), ('importar_preco_produto', 'Pode importar preços de produtos em lote'), ('visualizar_historico_preco_produto', 'Pode visualizar histórico de preços de produtos')]},
        ),
        migrations.AlterModelOptions(
            name='transferencia',
            options={'permissions': [('visualizar_transferencias', 'Pode visualizar transferências'), ('criar_transferencias', 'Pode criar transferências'), ('aprovar_transferencias', 'Pode aprovar transferências'), ('receber_transferencias', 'Pode receber transferências'), ('cancelar_transferencias', 'Pode cancelar transferências')]},
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_fonte',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_precificados', to='insumos.fornecedorinsumo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_origem',
            field=models.CharField(choices=[('DOCUMENTO_COMPRA', 'Documento de compra'), ('INFORMADO_COMPRAS', 'Informado por Compras'), ('ESTIMATIVA_MERCADO', 'Estimativa de mercado'), ('LEGADO', 'Valor legado'), ('SEM_PRECO_VALIDADO', 'Sem preço validado')], db_index=True, default='SEM_PRECO_VALIDADO', max_length=30),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_referencia',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_validado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_precos_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditoriaPermissaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao', models.CharField(db_index=True, max_length=150)),
                ('valor_anterior', models.BooleanField()),
                ('valor_novo', models.BooleanField()),
                ('alterado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alterado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_permissoes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_permissoes_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-alterado_em', '-id'],
                'indexes': [models.Index(fields=['usuario', 'alterado_em'], name='estoque_aud_usuario_9effb3_idx')],
            },
        ),
    ]
