# Generated by Django 5.2.6 on 2026-08-27 18:18

import django.core.validators
import django.db.models.deletion
import estoque.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0040_videodocumentacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolucaoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fabricante', models.CharField(max_length=120)),
                ('modelo', models.CharField(db_index=True, max_length=120)),
                ('categoria', models.CharField(default='Coletores', max_length=100)),
                ('resumo', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('arquivo', models.FileField(storage=estoque.models.resolucao_documento_storage, upload_to=estoque.models.resolucao_documento_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Envie um arquivo PDF.')])),
                ('nome_original', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolucoes_documentacao_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'relatório de resolução de problemas',
                'verbose_name_plural': 'relatórios de resolução de problemas',
                'ordering': ['fabricante', 'modelo', 'titulo'],
            },
        ),
    ]
