# Generated by Django 5.2.6 on 2026-09-03

import django.core.validators
import django.db.models.deletion
import estoque.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0041_resolucaodocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resolucaodocumento',
            name='idioma',
            field=models.CharField(choices=[('pt-br', 'Português (Brasil)'), ('es', 'Espanhol')], default='pt-br', max_length=10, verbose_name='Idioma do documento'),
        ),
        migrations.CreateModel(
            name='DriverImpressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('fabricante', models.CharField(max_length=120, verbose_name='Fabricante')),
                ('modelo', models.CharField(db_index=True, max_length=160, verbose_name='Modelo')),
                ('sistema_operacional', models.CharField(max_length=120, verbose_name='Sistema operacional')),
                ('arquitetura', models.CharField(blank=True, help_text='Ex.: 64 bits, 32 bits ou universal.', max_length=30, verbose_name='Arquitetura')),
                ('versao', models.CharField(blank=True, max_length=80, verbose_name='Versão')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('instrucoes', models.TextField(blank=True, verbose_name='Instruções de instalação')),
                ('arquivo', models.FileField(storage=estoque.models.driver_impressora_storage, upload_to=estoque.models.driver_impressora_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['exe', 'msi', 'zip', 'rar', 'cab', 'inf'], message='Envie um driver nos formatos EXE, MSI, ZIP, RAR, CAB ou INF.'), estoque.models.validar_tamanho_driver_impressora], verbose_name='Arquivo do driver')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho_bytes', models.PositiveBigIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drivers_impressora_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'driver de impressora',
                'verbose_name_plural': 'drivers de impressoras',
                'ordering': ['fabricante', 'modelo', 'sistema_operacional', '-atualizado_em'],
            },
        ),
    ]
