# Generated by Django 5.2.17 on 2026-09-05 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0043_empresa_metadados_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionamentoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relacionamentos_empresa_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionamentos_entrada', to='estoque.empresa')),
                ('empresa_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionamentos_saida', to='estoque.empresa')),
            ],
            options={
                'verbose_name': 'Relacionamento entre empresas',
                'verbose_name_plural': 'Relacionamentos entre empresas',
                'ordering': ('empresa_origem__nome', 'empresa_destino__nome'),
            },
        ),
        migrations.CreateModel(
            name='CapacidadeRelacionamentoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.CharField(choices=[('OPERACAO', 'Operação do tenant'), ('EQUIPAMENTOS', 'Equipamentos'), ('ESTOQUE', 'Estoque'), ('SICK', 'SICK'), ('TRANSFERENCIAS', 'Transferências'), ('EMPRESTIMOS', 'Empréstimos'), ('INSUMOS', 'Insumos'), ('CHECKLISTS', 'Checklists'), ('INVENTARIOS', 'Inventários'), ('CHAMADOS', 'Chamados'), ('COMPRAS', 'Compras'), ('CATALOGO', 'Catálogo'), ('ORDENS_SERVICO', 'Ordens de serviço'), ('AUDITORIAS', 'Auditorias'), ('DOCUMENTACAO', 'Documentação'), ('INTEGRACOES', 'Integrações'), ('TORY', 'Tory'), ('USUARIOS', 'Usuários')], max_length=30)),
                ('acao', models.CharField(choices=[('VISUALIZAR', 'Visualizar'), ('CRIAR', 'Criar'), ('EDITAR', 'Editar'), ('MOVIMENTAR', 'Movimentar'), ('ATENDER', 'Atender'), ('APROVAR', 'Aprovar'), ('EXPORTAR', 'Exportar'), ('ADMINISTRAR', 'Administrar')], max_length=20)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacidades_empresa_criadas', to=settings.AUTH_USER_MODEL)),
                ('relacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidades', to='estoque.relacionamentoempresa')),
            ],
            options={
                'verbose_name': 'Capability de relacionamento entre empresas',
                'verbose_name_plural': 'Capabilities de relacionamentos entre empresas',
                'ordering': ('relacionamento', 'recurso', 'acao'),
            },
        ),
        migrations.AddConstraint(
            model_name='relacionamentoempresa',
            constraint=models.UniqueConstraint(fields=('empresa_origem', 'empresa_destino'), name='empresa_relacao_direcional_unica'),
        ),
        migrations.AddConstraint(
            model_name='relacionamentoempresa',
            constraint=models.CheckConstraint(condition=models.Q(('empresa_origem', models.F('empresa_destino')), _negated=True), name='empresa_relacao_destinos_distintos'),
        ),
        migrations.AddIndex(
            model_name='capacidaderelacionamentoempresa',
            index=models.Index(fields=['ativo', 'recurso', 'acao'], name='empresa_cap_ativa_idx'),
        ),
        migrations.AddConstraint(
            model_name='capacidaderelacionamentoempresa',
            constraint=models.UniqueConstraint(fields=('relacionamento', 'recurso', 'acao'), name='empresa_relacao_capacidade_unica'),
        ),
    ]
