# Generated by Django 5.2.17 on 2026-09-11 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


MODULES = (
    ('estoque', 'Estoque'),
    ('equipamentos', 'Equipamentos'),
    ('sick', 'SICK'),
    ('transferencias', 'Transferências'),
    ('emprestimos', 'Empréstimos'),
    ('insumos', 'Insumos'),
    ('checklist', 'Checklist'),
    ('chamados', 'Chamados'),
    ('ordens_servico', 'Ordens de serviço'),
    ('catalogo', 'Catálogo'),
    ('tory', 'Tory'),
)


def seed_modules_and_existing_companies(apps, schema_editor):
    Module = apps.get_model('estoque', 'Modulo')
    Company = apps.get_model('estoque', 'Empresa')
    CompanyModule = apps.get_model('estoque', 'ModuloEmpresa')

    modules = []
    for order, (code, name) in enumerate(MODULES, start=1):
        module, _ = Module.objects.update_or_create(
            codigo=code,
            defaults={
                'nome': name,
                'ordem': order,
                'ativo': True,
            },
        )
        modules.append(module)

    CompanyModule.objects.bulk_create(
        [
            CompanyModule(
                empresa_id=company_id,
                modulo_id=module.pk,
                habilitado=True,
            )
            for company_id in Company.objects.values_list('pk', flat=True)
            for module in modules
        ],
        ignore_conflicts=True,
    )


def keep_seeded_data_on_reverse(apps, schema_editor):
    # As tabelas são removidas logo depois pelo rollback da migration.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0049_documentacao_por_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(choices=[('estoque', 'Estoque'), ('equipamentos', 'Equipamentos'), ('sick', 'SICK'), ('transferencias', 'Transferências'), ('emprestimos', 'Empréstimos'), ('insumos', 'Insumos'), ('checklist', 'Checklist'), ('chamados', 'Chamados'), ('ordens_servico', 'Ordens de serviço'), ('catalogo', 'Catálogo'), ('tory', 'Tory')], max_length=40, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Módulo da plataforma',
                'verbose_name_plural': 'Módulos da plataforma',
                'ordering': ('ordem', 'nome', 'codigo'),
            },
        ),
        migrations.CreateModel(
            name='ModuloEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('configurado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulos_empresa_configurados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_configurados', to='estoque.empresa')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas_configuradas', to='estoque.modulo')),
            ],
            options={
                'verbose_name': 'Módulo por empresa',
                'verbose_name_plural': 'Módulos por empresa',
                'ordering': ('empresa__nome', 'modulo__ordem', 'modulo__nome'),
                'indexes': [models.Index(fields=['empresa', 'habilitado'], name='empresa_modulo_habil_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'modulo'), name='empresa_modulo_unico')],
            },
        ),
        migrations.RunPython(
            seed_modules_and_existing_companies,
            reverse_code=keep_seeded_data_on_reverse,
        ),
    ]
