# Generated by Django 5.2.17 on 2026-09-19 19:56

import django.db.models.deletion
from django.db import migrations, models


COMPANY_SPECS = {
    'brasil': ('inventory-brasil', 'Inventory Brasil'),
    'latam': ('inventory-latam', 'Inventory Latam'),
    'oxxo': ('oxxo', 'OXXO'),
}

HISTORICAL_CATEGORIES = (
    'Coletores',
    'Impressoras',
    'Notebooks',
    'Routers',
)

DOCUMENTATION_SECTIONS = (
    'biblioteca',
    'manuais',
    'drivers',
    'resolucoes',
    'checklists',
    'videos',
)


def _resolve_inventory_companies(Empresa, *, using):
    matches = {}
    for key, (slug, name) in COMPANY_SPECS.items():
        matches[key] = list(
            Empresa.objects.using(using).filter(
                models.Q(slug__iexact=slug) | models.Q(nome__iexact=name)
            ).order_by('pk')
        )

    counts = {key: len(items) for key, items in matches.items()}
    if all(count == 0 for count in counts.values()):
        return {}
    if any(count != 1 for count in counts.values()):
        raise RuntimeError(
            'Não foi possível identificar de forma inequívoca Inventory Brasil, '
            f'Inventory Latam e OXXO. Correspondências: {counts}.'
        )

    companies = {key: items[0] for key, items in matches.items()}
    if len({company.pk for company in companies.values()}) != len(companies):
        raise RuntimeError(
            'Os tenants Inventory Brasil, Inventory Latam e OXXO devem ser distintos.'
        )
    return companies


def seed_existing_tenant_configuration(apps, schema_editor):
    using = schema_editor.connection.alias
    Empresa = apps.get_model('estoque', 'Empresa')
    Produto = apps.get_model('estoque', 'Produto')
    Equipamento = apps.get_model('estoque', 'Equipamento')
    Categoria = apps.get_model('estoque', 'CategoriaEquipamentoEmpresa')
    Secao = apps.get_model('estoque', 'SecaoDocumentacaoEmpresa')
    Video = apps.get_model('estoque', 'VideoDocumentacao')
    Resolucao = apps.get_model('estoque', 'ResolucaoDocumento')
    Driver = apps.get_model('estoque', 'DriverImpressora')
    Catalogo = apps.get_model('compras', 'CatalogoProdutoEmpresa')
    ChecklistDocumento = apps.get_model('insumos', 'ClienteChecklistDocumento')

    inventory_companies = _resolve_inventory_companies(Empresa, using=using)
    inventory_ids = {company.pk for company in inventory_companies.values()}

    legacy_product_categories = {
        value.strip()
        for value in Produto.objects.using(using).filter(
            empresa_catalogo_origem_id=None,
        )
        .exclude(categoria='')
        .values_list('categoria', flat=True)
        if value and value.strip()
    }

    categories_by_company = {}
    for company_id, category in Catalogo.objects.using(using).exclude(
        produto__categoria='',
    ).values_list('empresa_id', 'produto__categoria'):
        if company_id and category and category.strip():
            categories_by_company.setdefault(company_id, set()).add(category.strip())

    for company_id, category in Equipamento.objects.using(using).exclude(
        produto__categoria='',
    ).values_list('regional__empresa_id', 'produto__categoria'):
        if company_id and category and category.strip():
            categories_by_company.setdefault(company_id, set()).add(category.strip())

    for company_id, category in Produto.objects.using(using).exclude(
        empresa_catalogo_origem_id=None,
    ).exclude(categoria='').values_list('empresa_catalogo_origem_id', 'categoria'):
        if company_id and category and category.strip():
            categories_by_company.setdefault(company_id, set()).add(category.strip())

    inventory_categories = set(HISTORICAL_CATEGORIES) | legacy_product_categories
    for company_id in inventory_ids:
        categories_by_company.setdefault(company_id, set()).update(
            inventory_categories
        )

    for company_id, categories in categories_by_company.items():
        ordered = [
            category
            for category in HISTORICAL_CATEGORIES
            if category in categories
        ]
        ordered.extend(sorted(categories - set(ordered), key=str.casefold))
        Categoria.objects.using(using).bulk_create(
            [
                Categoria(
                    empresa_id=company_id,
                    nome=category,
                    ativo=True,
                    ordem=order,
                )
                for order, category in enumerate(ordered, start=1)
            ],
            ignore_conflicts=True,
        )

    sections_by_company = {
        company_id: set(DOCUMENTATION_SECTIONS)
        for company_id in inventory_ids
    }
    owned_section_sources = (
        ('videos', Video),
        ('resolucoes', Resolucao),
        ('drivers', Driver),
        ('checklists', ChecklistDocumento),
    )
    for section_code, model in owned_section_sources:
        for company_id in model.objects.using(using).exclude(
            empresa_id=None,
        ).values_list('empresa_id', flat=True).distinct():
            sections_by_company.setdefault(company_id, set()).add(section_code)

    for company_id, section_codes in sections_by_company.items():
        Secao.objects.using(using).bulk_create(
            [
                Secao(
                    empresa_id=company_id,
                    codigo=section_code,
                    habilitado=True,
                )
                for section_code in DOCUMENTATION_SECTIONS
                if section_code in section_codes
            ],
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_catalogoprodutoempresa'),
        ('estoque', '0051_empresa_slug_unico'),
        ('insumos', '0037_checklist_documento_por_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduloempresa',
            name='nome_exibicao',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='CategoriaEquipamentoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_equipamento', to='estoque.empresa')),
            ],
            options={
                'verbose_name': 'Categoria de equipamento por empresa',
                'verbose_name_plural': 'Categorias de equipamento por empresa',
                'ordering': ('empresa__nome', 'ordem', 'nome'),
                'indexes': [models.Index(fields=['empresa', 'ativo', 'ordem'], name='categoria_emp_ativa_ord_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'nome'), name='categoria_equipamento_empresa_unica')],
            },
        ),
        migrations.CreateModel(
            name='SecaoDocumentacaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('biblioteca', 'Biblioteca'), ('manuais', 'Manuais de equipamentos'), ('drivers', 'Drivers'), ('resolucoes', 'Resolução de problemas'), ('checklists', 'Checklist de clientes'), ('videos', 'Vídeos')], max_length=30)),
                ('habilitado', models.BooleanField(db_index=True, default=False)),
                ('nome_exibicao', models.CharField(blank=True, default='', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes_documentacao', to='estoque.empresa')),
            ],
            options={
                'verbose_name': 'Seção de documentação por empresa',
                'verbose_name_plural': 'Seções de documentação por empresa',
                'ordering': ('empresa__nome', 'codigo'),
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo'), name='secao_documentacao_empresa_unica'), models.CheckConstraint(condition=models.Q(('codigo__in', ('biblioteca', 'manuais', 'drivers', 'resolucoes', 'checklists', 'videos'))), name='secao_documentacao_codigo_valido')],
            },
        ),
        migrations.CreateModel(
            name='TermoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(choices=[('equipamento', 'Equipamento'), ('base', 'Base'), ('regional', 'Regional'), ('manutencao', 'Manutenção'), ('usuario', 'Usuário'), ('documentacao', 'Documentação')], max_length=100)),
                ('valor_singular', models.CharField(blank=True, default='', max_length=150)),
                ('valor_plural', models.CharField(blank=True, default='', max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_personalizados', to='estoque.empresa')),
            ],
            options={
                'verbose_name': 'Termo por empresa',
                'verbose_name_plural': 'Termos por empresa',
                'ordering': ('empresa__nome', 'chave'),
                'constraints': [models.UniqueConstraint(fields=('empresa', 'chave'), name='termo_empresa_unico'), models.CheckConstraint(condition=models.Q(('chave__in', ('equipamento', 'base', 'regional', 'manutencao', 'usuario', 'documentacao'))), name='termo_empresa_chave_valida')],
            },
        ),
        migrations.RunPython(
            seed_existing_tenant_configuration,
            migrations.RunPython.noop,
        ),
    ]
