# Generated by Django 5.2.17 on 2026-09-20 03:22

from django.conf import settings
from django.db import migrations, models


INVENTORY_COMPANIES = (
    ('inventory-brasil', 'Inventory Brasil'),
    ('inventory-latam', 'Inventory Latam'),
    ('oxxo', 'OXXO'),
)


def _inventory_company_ids(Empresa):
    company_ids = []
    for slug, name in INVENTORY_COMPANIES:
        company_id = Empresa.objects.filter(slug__iexact=slug).values_list(
            'pk', flat=True,
        ).first()
        if company_id is None:
            company_id = Empresa.objects.filter(nome__iexact=name).values_list(
                'pk', flat=True,
            ).first()
        if company_id is not None:
            company_ids.append(company_id)
    return company_ids


def preserve_explicit_catalogs(apps, schema_editor):
    Catalogo = apps.get_model('compras', 'CatalogoProdutoEmpresa')
    Empresa = apps.get_model('estoque', 'Empresa')
    Produto = apps.get_model('estoque', 'Produto')

    owner_links = [
        Catalogo(
            empresa_id=empresa_id,
            produto_id=produto_id,
            ativo=True,
        )
        for produto_id, empresa_id in Produto.objects.exclude(
            empresa_catalogo_origem_id=None,
        ).values_list('pk', 'empresa_catalogo_origem_id')
    ]
    Catalogo.objects.bulk_create(owner_links, ignore_conflicts=True)

    inventory_company_ids = _inventory_company_ids(Empresa)
    if not inventory_company_ids:
        return

    inventory_product_ids = list(
        Produto.objects.filter(
            models.Q(empresa_catalogo_origem_id=None)
            | models.Q(empresa_catalogo_origem_id__in=inventory_company_ids)
        ).values_list('pk', flat=True)
    )
    Catalogo.objects.bulk_create(
        [
            Catalogo(
                empresa_id=empresa_id,
                produto_id=produto_id,
                ativo=True,
            )
            for empresa_id in inventory_company_ids
            for produto_id in inventory_product_ids
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_catalogoprodutoempresa'),
        ('estoque', '0052_tenant_configuration_foundations'),
        ('insumos', '0037_checklist_documento_por_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa_catalogo_origem__isnull', False)), fields=('empresa_catalogo_origem', 'codigo'), name='produto_codigo_empresa_origem_unico'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa_catalogo_origem__isnull', True)), fields=('codigo',), name='produto_codigo_global_legado_unico'),
        ),
        migrations.RunPython(
            preserve_explicit_catalogs,
            migrations.RunPython.noop,
        ),
    ]
