# Generated by Django 5.2.17 on 2026-09-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0053_catalogo_fail_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoitem',
            name='categoria',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
