# Generated by Django 5.2.17 on 2026-09-21 01:12

from django.db import migrations, models


COMPANY_SPECS = (
    ('inventory-brasil', 'Inventory Brasil'),
    ('inventory-latam', 'Inventory Latam'),
    ('oxxo', 'OXXO'),
)


def preserve_inventory_dashboard_label(apps, schema_editor):
    Empresa = apps.get_model('estoque', 'Empresa')
    TermoEmpresa = apps.get_model('estoque', 'TermoEmpresa')
    using = schema_editor.connection.alias

    for slug, nome in COMPANY_SPECS:
        matches = list(
            Empresa.objects.using(using).filter(
                models.Q(slug__iexact=slug) | models.Q(nome__iexact=nome)
            ).order_by('pk')
        )
        if len(matches) > 1:
            raise RuntimeError(
                f'Empresa do Grupo Inventory ambígua para slug={slug!r}.'
            )
        if matches:
            TermoEmpresa.objects.using(using).get_or_create(
                empresa_id=matches[0].pk,
                chave='empresa',
                defaults={
                    'valor_singular': 'Inventory',
                    'valor_plural': 'Inventories',
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0054_categorias_dashboard_tenant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='termoempresa',
            name='termo_empresa_chave_valida',
        ),
        migrations.AlterField(
            model_name='termoempresa',
            name='chave',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('equipamento', 'Equipamento'), ('base', 'Base'), ('regional', 'Regional'), ('manutencao', 'Manutenção'), ('usuario', 'Usuário'), ('documentacao', 'Documentação')], max_length=100),
        ),
        migrations.AddConstraint(
            model_name='termoempresa',
            constraint=models.CheckConstraint(condition=models.Q(('chave__in', ('empresa', 'equipamento', 'base', 'regional', 'manutencao', 'usuario', 'documentacao'))), name='termo_empresa_chave_valida'),
        ),
        migrations.RunPython(
            preserve_inventory_dashboard_label,
            migrations.RunPython.noop,
        ),
    ]
