# Generated by Django 5.2.17 on 2026-09-22 20:56

from django.db import migrations, models


def preserve_inventory_rules(apps, schema_editor):
    from importlib import import_module
    resolver = import_module('estoque.migrations.0052_tenant_configuration_foundations')
    using = schema_editor.connection.alias
    companies = resolver._resolve_inventory_companies(apps.get_model('estoque', 'Empresa'), using=using)
    Category = apps.get_model('estoque', 'CategoriaEquipamentoEmpresa')
    aliases = {
        'Coletores': ['coletor', 'coletores', 'coletora', 'coletoras'],
        'Routers': ['router', 'routers', 'roteador', 'roteadores'],
        'Notebooks': ['notebook', 'notebooks'],
        'Impressoras': ['impressora', 'impressoras'],
    }
    for company in companies.values():
        for name, words in aliases.items():
            values = {'aliases': words}
            if name == 'Coletores':
                values.update(limite_checklist_por_pessoas=5, referencia_capacidade=True)
            Category.objects.using(using).filter(empresa_id=company.pk, nome__iexact=name).update(**values)


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0055_dashboard_empresa_terminologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaequipamentoempresa',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='categoriaequipamentoempresa',
            name='limite_checklist_por_pessoas',
            field=models.PositiveIntegerField(blank=True, help_text='Margem adicional ao número de pessoas. Vazio desabilita o limite.', null=True),
        ),
        migrations.AddField(
            model_name='categoriaequipamentoempresa',
            name='referencia_capacidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.RunPython(preserve_inventory_rules, migrations.RunPython.noop),
    ]
