# Generated by Django 5.2.17 on 2026-09-29 20:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0058_secao_documentacao_legado_explicito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperadoraMovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.SlugField(max_length=40)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadoras_moveis', to='estoque.empresa')),
            ],
            options={
                'verbose_name': 'Operadora móvel',
                'verbose_name_plural': 'Operadoras móveis',
                'ordering': ('empresa__nome', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='LinhaMovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_normalizado', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Informe o número no formato internacional E.164.', regex='^\\+[1-9]\\d{7,14}$')])),
                ('iccid', models.CharField(blank=True, default='', max_length=22, validators=[django.core.validators.RegexValidator(message='O ICCID deve conter de 18 a 22 dígitos.', regex='^\\d{18,22}$')])),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em uso'), ('SUSPENSA', 'Suspensa'), ('INATIVA', 'Inativa')], db_index=True, default='DISPONIVEL', max_length=15)),
                ('observacao', models.TextField(blank=True, default='')),
                ('ativada_em', models.DateTimeField(blank=True, null=True)),
                ('inativada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas_moveis', to='estoque.base')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas_moveis_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas_moveis', to='estoque.empresa')),
                ('operadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas_moveis', to='estoque.operadoramovel')),
            ],
            options={
                'verbose_name': 'Linha móvel',
                'verbose_name_plural': 'Linhas móveis',
                'ordering': ('empresa__nome', 'numero_normalizado'),
                'permissions': [('visualizar_linhas_moveis', 'Pode visualizar linhas móveis'), ('gerenciar_linhas_moveis', 'Pode gerenciar linhas móveis'), ('vincular_linhas_moveis', 'Pode vincular linhas móveis'), ('visualizar_credenciais_linhas_moveis', 'Pode visualizar credenciais de linhas móveis')],
            },
        ),
        migrations.CreateModel(
            name='VinculoLinhaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fim_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('motivo_fim', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('desvinculado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='desvinculos_linha_realizados', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_linha_movel', to='estoque.equipamento')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_equipamento', to='estoque.linhamovel')),
                ('vinculado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_linha_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo entre linha e equipamento',
                'verbose_name_plural': 'Vínculos entre linhas e equipamentos',
                'ordering': ('-inicio_em', '-id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricoLinhaMovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('CADASTRO', 'Cadastro'), ('ALTERACAO', 'Alteração'), ('ATIVACAO', 'Ativação'), ('INATIVACAO', 'Inativação'), ('VINCULO', 'Vínculo'), ('DESVINCULO', 'Desvínculo'), ('TROCA', 'Troca')], db_index=True, max_length=15)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_linhas_moveis', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_linhas_moveis', to='estoque.empresa')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='estoque.linhamovel')),
            ],
            options={
                'verbose_name': 'Histórico de linha móvel',
                'verbose_name_plural': 'Históricos de linhas móveis',
                'ordering': ('-criado_em', '-id'),
                'indexes': [models.Index(fields=['empresa', 'linha', 'criado_em'], name='hist_linha_escopo_data_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('evento__in', ('CADASTRO', 'ALTERACAO', 'ATIVACAO', 'INATIVACAO', 'VINCULO', 'DESVINCULO', 'TROCA'))), name='historico_linha_evento_valido')],
            },
        ),
        migrations.AddConstraint(
            model_name='operadoramovel',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='operadora_movel_empresa_codigo_unico'),
        ),
        migrations.AddConstraint(
            model_name='operadoramovel',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='operadora_movel_empresa_nome_unico'),
        ),
        migrations.AddIndex(
            model_name='linhamovel',
            index=models.Index(fields=['empresa', 'base', 'status'], name='linha_movel_escopo_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='linhamovel',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_normalizado'), name='linha_movel_empresa_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='linhamovel',
            constraint=models.UniqueConstraint(condition=models.Q(('iccid', ''), _negated=True), fields=('empresa', 'iccid'), name='linha_movel_empresa_iccid_unico'),
        ),
        migrations.AddConstraint(
            model_name='linhamovel',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('DISPONIVEL', 'EM_USO', 'SUSPENSA', 'INATIVA'))), name='linha_movel_status_valido'),
        ),
        migrations.AddConstraint(
            model_name='vinculolinhaequipamento',
            constraint=models.UniqueConstraint(condition=models.Q(('fim_em__isnull', True)), fields=('linha',), name='vinculo_linha_ativo_unico'),
        ),
        migrations.AddConstraint(
            model_name='vinculolinhaequipamento',
            constraint=models.UniqueConstraint(condition=models.Q(('fim_em__isnull', True)), fields=('equipamento',), name='vinculo_equipamento_ativo_unico'),
        ),
        migrations.AddConstraint(
            model_name='vinculolinhaequipamento',
            constraint=models.CheckConstraint(condition=models.Q(('fim_em__isnull', True), ('fim_em__gte', models.F('inicio_em')), _connector='OR'), name='vinculo_linha_periodo_valido'),
        ),
    ]
