# Generated by Django 5.2.17 on 2026-09-29 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0059_operadoramovel_linhamovel_vinculolinhaequipamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialLinhaMovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_criptografado', models.TextField()),
                ('chave_id', models.CharField(max_length=50)),
                ('campos_configurados', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credenciais_linhas_moveis_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('linha', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credencial_protegida', to='estoque.linhamovel')),
            ],
            options={
                'verbose_name': 'Credencial protegida de linha móvel',
                'verbose_name_plural': 'Credenciais protegidas de linhas móveis',
            },
        ),
    ]
