# Generated by Django 5.2 on 2026-10-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0060_credenciallinhamovel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='linhamovel',
            name='usuario_responsavel',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='linhas_moveis_sob_responsabilidade',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Usuário responsável',
            ),
        ),
    ]
