# Generated by Django 5.2 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0061_linhamovel_usuario_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='linhamovel',
            name='responsavel_nome',
            field=models.CharField(
                blank=True,
                default='',
                max_length=150,
                verbose_name='Colaborador responsável sem acesso',
            ),
        ),
    ]
