# Generated by Django 5.2.17 on 2026-10-06 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0062_linhamovel_responsavel_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('matricula', models.CharField(blank=True, max_length=50, verbose_name='Matrícula')),
                ('cargo_funcao', models.CharField(blank=True, max_length=120, verbose_name='Cargo/função')),
                ('setor', models.CharField(blank=True, max_length=120)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='estoque.base')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='estoque.empresa')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador_custodia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ('nome', 'id'),
                'indexes': [models.Index(fields=['empresa', 'ativo', 'base'], name='colaborador_escopo_ativo_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('matricula', ''), _negated=True), fields=('empresa', 'matricula'), name='colaborador_empresa_matricula_unica')],
            },
        ),
    ]
