# Generated by Django 5.2.17 on 2026-10-07 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0063_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('ESCRITORIO', 'Escritório'), ('BASE_LOGISTICA', 'Base Logística'), ('DEPOSITO', 'Depósito'), ('OUTRO', 'Outro')], max_length=20)),
                ('logradouro', models.CharField(max_length=180)),
                ('numero', models.CharField(max_length=30)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais_fisicos', to='estoque.empresa')),
            ],
            options={
                'verbose_name': 'Local físico',
                'verbose_name_plural': 'Locais físicos',
                'ordering': ('nome', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VinculoBaseLocalFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_local_fisico', to='estoque.base')),
                ('local_fisico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_base', to='estoque.localfisico')),
            ],
            options={
                'verbose_name': 'Vínculo de Base com local físico',
                'verbose_name_plural': 'Vínculos de Bases com locais físicos',
                'ordering': ('local_fisico', 'base'),
            },
        ),
        migrations.AddField(
            model_name='localfisico',
            name='bases',
            field=models.ManyToManyField(related_name='locais_fisicos', through='estoque.VinculoBaseLocalFisico', to='estoque.base'),
        ),
        migrations.AddConstraint(
            model_name='vinculobaselocalfisico',
            constraint=models.UniqueConstraint(fields=('local_fisico', 'base'), name='local_fisico_base_unica'),
        ),
        migrations.AddIndex(
            model_name='localfisico',
            index=models.Index(fields=['empresa', 'ativo', 'tipo'], name='local_fisico_escopo_idx'),
        ),
        migrations.AddConstraint(
            model_name='localfisico',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='local_fisico_empresa_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='localfisico',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ('ESCRITORIO', 'BASE_LOGISTICA', 'DEPOSITO', 'OUTRO'))), name='local_fisico_tipo_valido'),
        ),
    ]
