# Generated by Django 5.2.17 on 2026-10-08 15:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0064_localfisico_vinculobaselocalfisico_localfisico_bases_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Custodia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATIVA', 'Ativa'), ('EM_DEVOLUCAO', 'Em devolução'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], db_index=True, default='RASCUNHO', max_length=20)),
                ('condicao_geral', models.CharField(choices=[('NAO_INFORMADA', 'Não informada'), ('NOVO', 'Novo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('AVARIADO', 'Avariado')], default='NAO_INFORMADA', max_length=20, verbose_name='Condição geral na entrega')),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodias', to='estoque.base')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodias', to='estoque.colaborador')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodias', to='estoque.empresa')),
                ('local_fisico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custodias', to='estoque.localfisico')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custódia',
                'verbose_name_plural': 'Custódias',
                'ordering': ('-data_entrega', '-id'),
                'indexes': [models.Index(fields=['empresa', 'status', 'data_entrega'], name='custodia_empresa_status_idx'), models.Index(fields=['colaborador', 'status'], name='custodia_colab_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('RASCUNHO', 'ATIVA', 'EM_DEVOLUCAO', 'FINALIZADA', 'CANCELADA'))), name='custodia_status_valido'), models.CheckConstraint(condition=models.Q(('condicao_geral__in', ('NAO_INFORMADA', 'NOVO', 'BOM', 'REGULAR', 'AVARIADO'))), name='custodia_condicao_geral_valida')],
            },
        ),
    ]
