class GruposInsumos:

    SOLICITANTE = 'INSUMOS_SOLICITANTE'
    COMPRAS = 'INSUMOS_COMPRAS'
    PLANEJAMENTO = 'INSUMOS_PLANEJAMENTO'
    FINANCEIRO = 'INSUMOS_FINANCEIRO'
    EXECUTIVO = 'INSUMOS_EXECUTIVO'

    TODOS = [
        SOLICITANTE,
        COMPRAS,
        PLANEJAMENTO,
        FINANCEIRO,
        EXECUTIVO,
    ]