# Generated by Django 5.2.6 on 2026-08-11 18:33

import chamados.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0036_restringir_manutencao_matriz'),
        ('insumos', '0030_corrigir_unidade_epis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('sla_horas', models.PositiveIntegerField(default=24)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
                'permissions': [('gerenciar_categorias_chamado', 'Pode gerenciar categorias de chamados')],
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(editable=False, max_length=30, unique=True)),
                ('loja', models.CharField(blank=True, max_length=100)),
                ('lider', models.CharField(blank=True, max_length=150)),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField()),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], db_index=True, default='NORMAL', max_length=12)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ATENDIMENTO', 'Em atendimento'), ('AGUARDANDO_USUARIO', 'Aguardando usuário'), ('RESOLVIDO', 'Resolvido'), ('FECHADO', 'Fechado'), ('CANCELADO', 'Cancelado')], db_index=True, default='ABERTO', max_length=24)),
                ('aberto_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('prazo_sla_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('resolucao', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aberto_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados_abertos', to=settings.AUTH_USER_MODEL)),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chamados_atendidos', to=settings.AUTH_USER_MODEL)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='estoque.base')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='chamados.categoriachamado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='estoque.empresa')),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='insumos.inventario')),
            ],
            options={
                'ordering': ['-aberto_em', '-id'],
                'permissions': [('atender_chamado', 'Pode atender chamados'), ('visualizar_todos_chamados', 'Pode visualizar todos os chamados'), ('exportar_chamados', 'Pode exportar chamados')],
            },
        ),
        migrations.CreateModel(
            name='ChamadoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='chamados.chamado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChamadoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('nota_interna', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens_chamados', to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chamados.chamado')),
            ],
            options={
                'ordering': ['criado_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChamadoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=chamados.models.caminho_anexo, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'webp', 'txt', 'csv', 'xlsx', 'docx']), chamados.models.validar_tamanho_anexo])),
                ('nome_original', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='chamados.chamado')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('mensagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='chamados.chamadomensagem')),
            ],
        ),
        migrations.CreateModel(
            name='SequenciaChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.empresa')),
            ],
        ),
        migrations.AddIndex(
            model_name='chamado',
            index=models.Index(fields=['empresa', 'status', 'aberto_em'], name='chamados_ch_empresa_2c92ca_idx'),
        ),
        migrations.AddIndex(
            model_name='chamado',
            index=models.Index(fields=['base', 'status'], name='chamados_ch_base_id_3a291f_idx'),
        ),
        migrations.AddIndex(
            model_name='chamado',
            index=models.Index(fields=['atendente', 'status'], name='chamados_ch_atenden_c7c448_idx'),
        ),
        migrations.AddConstraint(
            model_name='sequenciachamado',
            constraint=models.UniqueConstraint(fields=('empresa', 'ano'), name='chamado_sequencia_empresa_ano_unica'),
        ),
    ]
