# Generated by Django 5.2.6 on 2026-08-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_chamados_avancados'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='categoria_equipamento',
            field=models.CharField(blank=True, choices=[('Coletores', 'Coletores'), ('Impressoras', 'Impressoras'), ('Notebooks', 'Notebooks'), ('Routers', 'Routers')], db_index=True, max_length=50),
        ),
    ]
