# Generated by Django 5.2.6 on 2026-08-13 17:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_alter_chamado_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='momento_inventario_abertura',
            field=models.CharField(blank=True, choices=[('ANTES', 'Antes do inventario'), ('EM_ANDAMENTO', 'Inventario em andamento')], db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='categoria_equipamento',
            field=models.CharField(blank=True, choices=[('Sistema', 'Sistema'), ('Coletores', 'Coletores'), ('Notebooks', 'Notebooks'), ('Impressoras', 'Impressoras'), ('Routers', 'Routers')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ChamadoConexaoAtendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=255, unique=True)),
                ('conectado_em', models.DateTimeField(auto_now_add=True)),
                ('visto_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_presenca_chamados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'visto_em'], name='chamados_ch_usuario_87feb1_idx')],
            },
        ),
    ]
