# Generated by Django 5.2.6 on 2026-08-20 16:34

import chamados.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0008_exigir_atendimento_na_avaliacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamado',
            options={'ordering': ['-aberto_em', '-id'], 'permissions': [('abrir_chamado', 'Pode abrir chamados'), ('atender_chamado', 'Pode atender chamados'), ('visualizar_todos_chamados', 'Pode visualizar todos os chamados'), ('exportar_chamados', 'Pode exportar chamados'), ('supervisionar_chamado', 'Pode supervisionar chamados'), ('visualizar_dashboard_chamado', 'Pode visualizar dashboard de chamados'), ('configurar_chamado', 'Pode configurar chamados e vínculos'), ('converter_chamado_sick', 'Pode converter chamado em SICK'), ('reabrir_chamado', 'Pode reabrir chamados')]},
        ),
        migrations.AlterField(
            model_name='chamadoanexo',
            name='arquivo',
            field=models.FileField(storage=chamados.models.armazenamento_privado_chamados, upload_to=chamados.models.caminho_anexo, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'webp', 'txt', 'csv', 'xlsx', 'docx', 'rar', 'exe']), chamados.models.validar_tamanho_anexo, chamados.models.validar_mime_anexo]),
        ),
    ]
