# Generated by Django 5.2.6 on 2026-08-20 16:38

import chamados.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0009_alter_chamado_options_alter_chamadoanexo_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadoanexo',
            name='arquivo',
            field=models.FileField(storage=chamados.models.armazenamento_privado_chamados, upload_to=chamados.models.caminho_anexo, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'webp', 'txt', 'csv', 'xlsx', 'docx', 'rar', 'exe']), chamados.models.validar_tamanho_anexo, chamados.models.validar_mime_anexo, chamados.models.validar_assinatura_anexo]),
        ),
    ]
