# Generated by Django 5.2.17 on 2026-09-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0011_tipo_chamado_e_base_opcional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='categoria_equipamento',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
