# Generated by Django 5.2.6 on 2026-06-15 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0025_alter_emprestimo_status_alter_itememprestimo_status'),
        ('insumos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='insumo',
            name='estoque_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='valor_medio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='solicitacaoinsumo',
            name='finalizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoinsumo',
            name='finalizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_finalizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaoinsumo',
            name='observacao_aprovacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoinsumo',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('DEVOLUCAO', 'Devolução'), ('AJUSTE_ENTRADA', 'Ajuste Entrada'), ('AJUSTE_SAIDA', 'Ajuste Saída'), ('PERDA', 'Perda')], max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SOLICITACAO', 'Solicitação'), ('APROVACAO', 'Aprovação'), ('MOVIMENTACAO', 'Movimentação'), ('CHECKLIST', 'Checklist'), ('CONSUMO', 'Consumo')], max_length=30)),
                ('descricao', models.TextField()),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja', models.CharField(db_index=True, max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado')], default='PLANEJADO', max_length=20)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.base')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='insumos.cliente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_EXECUCAO', 'Em execução'), ('FINALIZADO', 'Finalizado')], default='ABERTO', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists_criados', to=settings.AUTH_USER_MODEL)),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklists_finalizados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='insumos.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_enviada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantidade_utilizada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantidade_retornada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantidade_perdida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='insumos.checklistdiario')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.insumo')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.inventario')),
                ('item_checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.itemchecklist')),
            ],
        ),
        migrations.CreateModel(
            name='LoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inicial', models.IntegerField()),
                ('numero_final', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.base')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inicial', models.IntegerField()),
                ('numero_final', models.IntegerField()),
                ('tipo', models.CharField(choices=[('ENVIO', 'Envio'), ('RETORNO', 'Retorno'), ('PERDA', 'Perda')], max_length=20)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.inventario')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.lotetag')),
            ],
        ),
    ]
