# Generated by Django 5.2.6 on 2026-06-16 20:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0025_alter_emprestimo_status_alter_itememprestimo_status'),
        ('insumos', '0002_cliente_insumo_estoque_maximo_insumo_valor_medio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolicitacaoinsumo',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itemsolicitacaoinsumo',
            name='quantidade_atendida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lotetag',
            name='quantidade_disponivel',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='lotetag',
            name='quantidade_total',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='movimentacaotag',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacaotag',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaoinsumo',
            name='em_compra_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoinsumo',
            name='em_compra_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_em_compra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaoinsumo',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='itemchecklist',
            unique_together={('checklist', 'insumo')},
        ),
        migrations.AddIndex(
            model_name='checklistdiario',
            index=models.Index(fields=['status'], name='insumos_che_status_db80fa_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistdiario',
            index=models.Index(fields=['data_inicio'], name='insumos_che_data_in_bda12e_idx'),
        ),
        migrations.AddIndex(
            model_name='consumoinsumo',
            index=models.Index(fields=['inventario'], name='insumos_con_inventa_fb5776_idx'),
        ),
        migrations.AddIndex(
            model_name='consumoinsumo',
            index=models.Index(fields=['insumo'], name='insumos_con_insumo__242cab_idx'),
        ),
        migrations.AddIndex(
            model_name='consumoinsumo',
            index=models.Index(fields=['criado_em'], name='insumos_con_criado__af8df3_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoinsumo',
            index=models.Index(fields=['tipo'], name='insumos_his_tipo_3c1119_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoinsumo',
            index=models.Index(fields=['criado_em'], name='insumos_his_criado__02423a_idx'),
        ),
        migrations.AddIndex(
            model_name='lotetag',
            index=models.Index(fields=['base'], name='insumos_lot_base_id_45c662_idx'),
        ),
        migrations.AddIndex(
            model_name='lotetag',
            index=models.Index(fields=['ativo'], name='insumos_lot_ativo_7c4dad_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoinsumo',
            index=models.Index(fields=['base', 'insumo'], name='insumos_mov_base_id_3c13df_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoinsumo',
            index=models.Index(fields=['tipo'], name='insumos_mov_tipo_dbecb0_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoinsumo',
            index=models.Index(fields=['criado_em'], name='insumos_mov_criado__d3a354_idx'),
        ),
    ]
