# Generated by Django 5.2.6 on 2026-06-17 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0003_itemsolicitacaoinsumo_observacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistdiario',
            options={'permissions': [('gerenciar_checklists', 'Pode gerenciar checklists'), ('finalizar_checklists', 'Pode finalizar checklists')]},
        ),
        migrations.AlterModelOptions(
            name='consumoinsumo',
            options={'permissions': [('visualizar_custos', 'Pode visualizar custos'), ('visualizar_dashboards_financeiros', 'Pode visualizar dashboards financeiros')]},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'permissions': [('gerenciar_inventarios', 'Pode gerenciar inventários')]},
        ),
        migrations.AlterModelOptions(
            name='lotetag',
            options={'permissions': [('gerenciar_tags', 'Pode gerenciar TAGs')]},
        ),
        migrations.AlterModelOptions(
            name='movimentacaoinsumo',
            options={'permissions': [('realizar_entrada', 'Pode registrar entradas'), ('realizar_saida', 'Pode registrar saídas'), ('realizar_devolucao', 'Pode registrar devoluções'), ('realizar_perda', 'Pode registrar perdas'), ('realizar_ajuste', 'Pode realizar ajustes')]},
        ),
        migrations.AlterModelOptions(
            name='solicitacaoinsumo',
            options={'permissions': [('aprovar_solicitacao', 'Pode aprovar solicitações'), ('reprovar_solicitacao', 'Pode reprovar solicitações'), ('colocar_em_compra', 'Pode enviar solicitação para compras'), ('finalizar_solicitacao', 'Pode finalizar solicitações')]},
        ),
        migrations.AlterField(
            model_name='movimentacaotag',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
