# Generated by Django 5.2.6 on 2026-06-22 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0026_alter_equipamento_status'),
        ('insumos', '0004_alter_checklistdiario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistLoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inicial_enviado', models.IntegerField()),
                ('numero_final_enviado', models.IntegerField()),
                ('numero_inicial_retornado', models.IntegerField(blank=True, null=True)),
                ('numero_final_retornado', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('RETORNADO', 'Retornado')], default='ENVIADO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_tags_movimentados', to='insumos.checklistdiario')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.lotetag')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_saida', models.CharField(max_length=100, verbose_name='Nº Tag na Saída')),
                ('tag_volta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Tag na Volta')),
                ('data_retorno', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos_utilizados', to='insumos.checklistdiario')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.equipamento')),
            ],
            options={
                'unique_together': {('checklist', 'equipamento')},
            },
        ),
    ]
