# Generated by Django 5.2.6 on 2026-06-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0005_checklistlotetag_checklistequipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
