# Generated by Django 5.2.6 on 2026-06-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0006_inventario_bairro_inventario_cep_inventario_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='dados_brutos',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
