# Generated by Django 5.2.6 on 2026-06-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0007_add_dados_brutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='bid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='chave',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='data_visita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='envio_escala',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='equipe_plan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='historico_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='historico_equipe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='historico_lider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='historico_pecas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='historico_preparacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='historico_satisfacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='horario_ponto',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='horario_visita',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='lider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='pessoas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='ponto_encontro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='prep',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='previsao_pecas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='prod_media',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='relatorio_visita',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='responsavel_visita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipo_visita',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
