# Generated by Django 5.2.6 on 2026-07-02 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0008_add_inventario_campos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistlotetag',
            options={'verbose_name': 'Lote de TAG do checklist', 'verbose_name_plural': 'Lotes de TAG do checklist'},
        ),
        migrations.RenameField(
            model_name='checklistlotetag',
            old_name='numero_final_retornado',
            new_name='numero_final_utilizado',
        ),
        migrations.RenameField(
            model_name='checklistlotetag',
            old_name='numero_final_enviado',
            new_name='numero_inicial_utilizado',
        ),
        migrations.RemoveField(
            model_name='checklistlotetag',
            name='numero_inicial_enviado',
        ),
        migrations.RemoveField(
            model_name='checklistlotetag',
            name='numero_inicial_retornado',
        ),
        migrations.RemoveField(
            model_name='checklistlotetag',
            name='status',
        ),
        migrations.AlterField(
            model_name='checklistlotetag',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists_utilizados', to='insumos.lotetag'),
        ),
        migrations.AlterField(
            model_name='movimentacaotag',
            name='tipo',
            field=models.CharField(choices=[('UTILIZACAO', 'Utilização em inventário'), ('PERDA', 'Perda'), ('AJUSTE', 'Ajuste')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='checklistlotetag',
            index=models.Index(fields=['checklist'], name='insumos_che_checkli_4ed6f4_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistlotetag',
            index=models.Index(fields=['lote'], name='insumos_che_lote_id_6bd4ce_idx'),
        ),
    ]
