# Generated by Django 5.2.6 on 2026-07-12 22:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0015_cliente_status_relatorio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, unique=True)),
                ('documento', models.CharField(blank=True, db_index=True, max_length=30)),
                ('contato', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('prazo_entrega_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='historicoinsumo',
            name='tipo',
            field=models.CharField(choices=[('SOLICITACAO', 'Solicitação'), ('APROVACAO', 'Aprovação'), ('MOVIMENTACAO', 'Movimentação'), ('CHECKLIST', 'Checklist'), ('CONSUMO', 'Consumo'), ('PRECO', 'Preço')], max_length=30),
        ),
        migrations.CreateModel(
            name='PrecoFornecedorInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('vigente_ate', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precos_insumos_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precos', to='insumos.fornecedorinsumo')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precos_fornecedores', to='insumos.insumo')),
            ],
            options={
                'ordering': ['-vigente_desde', '-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='insumo',
            name='preco_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_como_referencia', to='insumos.precofornecedorinsumo'),
        ),
        migrations.AddIndex(
            model_name='precofornecedorinsumo',
            index=models.Index(fields=['insumo', 'ativo'], name='insumos_pre_insumo__aa4808_idx'),
        ),
        migrations.AddIndex(
            model_name='precofornecedorinsumo',
            index=models.Index(fields=['fornecedor', 'ativo'], name='insumos_pre_fornece_0592c3_idx'),
        ),
        migrations.AddIndex(
            model_name='precofornecedorinsumo',
            index=models.Index(fields=['vigente_desde'], name='insumos_pre_vigente_94ca38_idx'),
        ),
        migrations.AddConstraint(
            model_name='precofornecedorinsumo',
            constraint=models.CheckConstraint(condition=models.Q(('valor_unitario__gt', 0)), name='preco_insumo_valor_positivo'),
        ),
    ]
