# Generated by Django 5.2.6 on 2026-07-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0016_fornecedorinsumo_alter_historicoinsumo_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedorinsumo',
            name='documento',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
