# Generated by Django 5.2.6 on 2026-07-12 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0017_alter_fornecedorinsumo_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PesquisaPrecoOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=255)),
                ('fonte', models.CharField(default='MERCADO_LIVRE', max_length=40)),
                ('pesquisado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesquisas_preco', to='insumos.insumo')),
                ('pesquisado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pesquisado_em'],
            },
        ),
        migrations.CreateModel(
            name='OfertaPrecoOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(max_length=40)),
                ('codigo_externo', models.CharField(max_length=80)),
                ('titulo', models.CharField(max_length=255)),
                ('vendedor', models.CharField(blank=True, max_length=160)),
                ('url', models.URLField(max_length=500)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frete', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frete_conhecido', models.BooleanField(default=False)),
                ('condicao', models.CharField(blank=True, max_length=30)),
                ('coletado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas_online', to='insumos.insumo')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='insumos.pesquisaprecoonline')),
            ],
            options={
                'ordering': ['preco_total', 'titulo'],
                'indexes': [models.Index(fields=['insumo', 'coletado_em'], name='insumos_ofe_insumo__6efa09_idx'), models.Index(fields=['fonte', 'codigo_externo'], name='insumos_ofe_fonte_619c1d_idx')],
            },
        ),
    ]
