# Generated by Django 5.2.6 on 2026-08-11 17:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def reconstruir_saldos_historicos(apps, schema_editor):
    Movimentacao = apps.get_model('insumos', 'MovimentacaoInsumo')
    Saldo = apps.get_model('insumos', 'SaldoInsumoBase')
    entradas = {'ENTRADA', 'DEVOLUCAO', 'AJUSTE_ENTRADA'}
    saidas = {'SAIDA', 'PERDA', 'AJUSTE_SAIDA'}
    acumulados = {}

    movimentos = Movimentacao.objects.order_by('base_id', 'insumo_id', 'criado_em', 'pk')
    for movimento in movimentos.iterator(chunk_size=2000):
        chave = (movimento.base_id, movimento.insumo_id)
        saldo, custo, ultima_entrada = acumulados.get(
            chave,
            (Decimal('0'), Decimal('0'), None),
        )
        quantidade = Decimal(movimento.quantidade)
        valor = Decimal(movimento.valor_unitario or 0)
        if movimento.tipo in entradas:
            novo_saldo = saldo + quantidade
            if quantidade > 0 and valor > 0 and novo_saldo > 0:
                custo = ((saldo * custo) + (quantidade * valor)) / novo_saldo
            saldo = novo_saldo
            ultima_entrada = movimento.criado_em
        elif movimento.tipo in saidas:
            saldo -= quantidade
        if saldo < 0:
            raise RuntimeError(
                f'Saldo histórico negativo em base={movimento.base_id}, '
                f'insumo={movimento.insumo_id}, movimentacao={movimento.pk}.'
            )
        acumulados[chave] = (saldo, custo, ultima_entrada)

    Saldo.objects.bulk_create([
        Saldo(
            base_id=base_id,
            insumo_id=insumo_id,
            saldo=saldo,
            custo_medio=custo,
            ultima_entrada_em=ultima_entrada,
        )
        for (base_id, insumo_id), (saldo, custo, ultima_entrada) in acumulados.items()
    ], batch_size=1000)


def remover_saldos_derivados(apps, schema_editor):
    apps.get_model('insumos', 'SaldoInsumoBase').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0034_perfil_bases_escopo_compras_and_more'),
        ('insumos', '0026_termos_pesquisa_online'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacaoinsumo',
            options={'permissions': [('realizar_entrada', 'Pode registrar entradas'), ('realizar_saida', 'Pode registrar saídas'), ('realizar_devolucao', 'Pode registrar devoluções'), ('realizar_perda', 'Pode registrar perdas'), ('realizar_ajuste', 'Pode realizar ajustes'), ('visualizar_valores_estoque', 'Pode visualizar valores do estoque'), ('gerenciar_fornecedores', 'Pode gerenciar fornecedores'), ('gerenciar_precos', 'Pode gerenciar preços'), ('gerenciar_aquisicoes', 'Pode gerenciar aquisições'), ('criar_remessa_compra', 'Pode criar remessa de compra'), ('confirmar_remessa_compra', 'Pode confirmar remessa de compra')]},
        ),
        migrations.CreateModel(
            name='SaldoInsumoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('custo_medio', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('ultima_entrada_em', models.DateTimeField(blank=True, null=True)),
                ('recalculado_em', models.DateTimeField(auto_now=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_insumos', to='estoque.base')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_por_base', to='insumos.insumo')),
            ],
            options={
                'ordering': ['base__nome', 'insumo__descricao'],
                'indexes': [models.Index(fields=['base', 'saldo'], name='insumos_sal_base_id_f5e479_idx'), models.Index(fields=['insumo', 'saldo'], name='insumos_sal_insumo__54ff57_idx')],
                'constraints': [models.UniqueConstraint(fields=('base', 'insumo'), name='saldo_insumo_base_unico'), models.CheckConstraint(condition=models.Q(('saldo__gte', 0)), name='saldo_insumo_base_nao_negativo'), models.CheckConstraint(condition=models.Q(('custo_medio__gte', 0)), name='custo_medio_insumo_base_nao_negativo')],
            },
        ),
        migrations.RunPython(reconstruir_saldos_historicos, remover_saldos_derivados),
    ]
