# Generated by Django 5.2.6 on 2026-08-11 17:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def reconstruir_saldos_historicos(apps, schema_editor):
    Movimentacao = apps.get_model(
        'insumos',
        'MovimentacaoInsumo',
    )
    Saldo = apps.get_model(
        'insumos',
        'SaldoInsumoBase',
    )
    Insumo = apps.get_model(
        'insumos',
        'Insumo',
    )

    entradas = {
        'ENTRADA',
        'DEVOLUCAO',
        'AJUSTE_ENTRADA',
    }

    saidas = {
        'SAIDA',
        'PERDA',
        'AJUSTE_SAIDA',
    }

    acumulados = {}

    movimentos = Movimentacao.objects.order_by(
        'base_id',
        'insumo_id',
        'pk',
    )

    for movimento in movimentos.iterator(chunk_size=2000):
        chave = (
            movimento.base_id,
            movimento.insumo_id,
        )

        dados = acumulados.setdefault(
            chave,
            {
                'saldo': Decimal('0'),
                'valor_estoque': Decimal('0'),
                'ultima_entrada': None,
            },
        )

        quantidade = Decimal(
            movimento.quantidade or 0
        )

        valor_unitario = Decimal(
            movimento.valor_unitario or 0
        )

        if quantidade < 0:
            raise RuntimeError(
                'Quantidade histórica negativa encontrada '
                f'em base={movimento.base_id}, '
                f'insumo={movimento.insumo_id}, '
                f'movimentacao={movimento.pk}.'
            )

        if movimento.tipo in entradas:
            dados['saldo'] += quantidade

            dados['valor_estoque'] += (
                quantidade * valor_unitario
            )

            if movimento.criado_em:
                if (
                    dados['ultima_entrada'] is None
                    or movimento.criado_em
                    > dados['ultima_entrada']
                ):
                    dados['ultima_entrada'] = (
                        movimento.criado_em
                    )

        elif movimento.tipo in saidas:
            dados['saldo'] -= quantidade

            dados['valor_estoque'] -= (
                quantidade * valor_unitario
            )

        else:
            raise RuntimeError(
                'Tipo de movimentação histórica '
                f'não reconhecido: {movimento.tipo}. '
                f'Movimentação={movimento.pk}.'
            )

    valores_legados = dict(
        Insumo.objects.values_list(
            'pk',
            'valor_medio',
        )
    )

    saldos_para_criar = []

    for (
        base_id,
        insumo_id,
    ), dados in acumulados.items():

        saldo = dados['saldo']
        valor_estoque = dados['valor_estoque']

        # Aqui está a validação importante:
        # o estado ATUAL nunca pode ser negativo.
        if saldo < 0:
            raise RuntimeError(
                'Saldo final negativo encontrado durante '
                'a migração: '
                f'base={base_id}, '
                f'insumo={insumo_id}, '
                f'saldo={saldo}.'
            )

        if saldo == 0:
            custo_medio = Decimal('0')

        elif valor_estoque > 0:
            custo_medio = (
                valor_estoque / saldo
            )

        else:
            # Histórico legado sem informação suficiente
            # de valoração.
            #
            # Usa o valor médio global anterior apenas como
            # valor inicial de compatibilidade.
            custo_medio = Decimal(
                valores_legados.get(insumo_id)
                or 0
            )

        if custo_medio < 0:
            raise RuntimeError(
                'Custo médio negativo encontrado durante '
                'a migração: '
                f'base={base_id}, '
                f'insumo={insumo_id}, '
                f'custo={custo_medio}.'
            )

        saldos_para_criar.append(
            Saldo(
                base_id=base_id,
                insumo_id=insumo_id,
                saldo=saldo,
                custo_medio=custo_medio,
                ultima_entrada_em=(
                    dados['ultima_entrada']
                ),
            )
        )

    Saldo.objects.bulk_create(
        saldos_para_criar,
        batch_size=1000,
    )


def remover_saldos_derivados(apps, schema_editor):
    apps.get_model('insumos', 'SaldoInsumoBase').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0034_perfil_bases_escopo_compras_and_more'),
        ('insumos', '0026_termos_pesquisa_online'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacaoinsumo',
            options={'permissions': [('realizar_entrada', 'Pode registrar entradas'), ('realizar_saida', 'Pode registrar saídas'), ('realizar_devolucao', 'Pode registrar devoluções'), ('realizar_perda', 'Pode registrar perdas'), ('realizar_ajuste', 'Pode realizar ajustes'), ('visualizar_valores_estoque', 'Pode visualizar valores do estoque'), ('gerenciar_fornecedores', 'Pode gerenciar fornecedores'), ('gerenciar_precos', 'Pode gerenciar preços'), ('gerenciar_aquisicoes', 'Pode gerenciar aquisições'), ('criar_remessa_compra', 'Pode criar remessa de compra'), ('confirmar_remessa_compra', 'Pode confirmar remessa de compra')]},
        ),
        migrations.CreateModel(
            name='SaldoInsumoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('custo_medio', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('ultima_entrada_em', models.DateTimeField(blank=True, null=True)),
                ('recalculado_em', models.DateTimeField(auto_now=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_insumos', to='estoque.base')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_por_base', to='insumos.insumo')),
            ],
            options={
                'ordering': ['base__nome', 'insumo__descricao'],
                'indexes': [models.Index(fields=['base', 'saldo'], name='insumos_sal_base_id_f5e479_idx'), models.Index(fields=['insumo', 'saldo'], name='insumos_sal_insumo__54ff57_idx')],
                'constraints': [models.UniqueConstraint(fields=('base', 'insumo'), name='saldo_insumo_base_unico'), models.CheckConstraint(condition=models.Q(('saldo__gte', 0)), name='saldo_insumo_base_nao_negativo'), models.CheckConstraint(condition=models.Q(('custo_medio__gte', 0)), name='custo_medio_insumo_base_nao_negativo')],
            },
        ),
        migrations.RunPython(reconstruir_saldos_historicos, remover_saldos_derivados),
    ]
