# Generated by Django 5.2.6 on 2026-08-11 18:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0035_equipamento_condicao_valor_and_more'),
        ('insumos', '0027_alter_movimentacaoinsumo_options_saldoinsumobase'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedorinsumo',
            name='canais_alternativos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fornecedorinsumo',
            name='condicoes_pagamento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fornecedorinsumo',
            name='contato_financeiro',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='fornecedorinsumo',
            name='contato_suporte',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='fornecedorinsumo',
            name='email_financeiro',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='fornecedorinsumo',
            name='email_suporte',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='fornecedorinsumo',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='fornecedorinsumo',
            name='politica_frete',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='saldoinsumobase',
            name='saldo_reservado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='saldoinsumobase',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_reservado__gte', 0)), name='saldo_insumo_reservado_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='saldoinsumobase',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_reservado__lte', models.F('saldo'))), name='saldo_insumo_reservado_ate_saldo'),
        ),
    ]
