# Generated by Django 5.2.6 on 2026-08-11 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0028_fornecedorinsumo_canais_alternativos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCadastroInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(db_index=True, max_length=60)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_novo', models.TextField(blank=True)),
                ('motivo', models.TextField()),
                ('origem', models.CharField(blank=True, db_index=True, max_length=80)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alteracoes_cadastro_insumo', to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_cadastro', to='insumos.insumo')),
            ],
            options={
                'ordering': ['-alterado_em', '-id'],
            },
        ),
    ]
