# Generated by Django 5.2.6 on 2026-08-20 16:34

import django.db.models.deletion
import unicodedata
from django.conf import settings
from django.db import migrations, models


def padronizar_epis_como_unidade(apps, schema_editor):
    Insumo = apps.get_model('insumos', 'Insumo')
    Historico = apps.get_model('insumos', 'HistoricoCadastroInsumo')
    origem = 'MIGRACAO_EPI_UN_20260820'
    for insumo in Insumo.objects.exclude(unidade_medida='UN').iterator():
        descricao = unicodedata.normalize('NFKD', insumo.descricao or '')
        descricao = ''.join(c for c in descricao if not unicodedata.combining(c)).upper()
        if not set(descricao.split()).intersection({
            'MASCARA', 'MASCARAS', 'TOUCA', 'TOUCAS', 'LUVA', 'LUVAS',
        }):
            continue
        if not Historico.objects.filter(insumo_id=insumo.pk, origem=origem).exists():
            Historico.objects.create(
                insumo_id=insumo.pk,
                campo='unidade_medida',
                valor_anterior=insumo.unidade_medida,
                valor_novo='UN',
                motivo='PADRONIZAÇÃO DE MÁSCARA, TOUCA E LUVA COMO UNIDADE.',
                origem=origem,
            )
        Insumo.objects.filter(pk=insumo.pk).update(unidade_medida='UN')


def reverter_padronizacao_epis(apps, schema_editor):
    Insumo = apps.get_model('insumos', 'Insumo')
    Historico = apps.get_model('insumos', 'HistoricoCadastroInsumo')
    historicos = Historico.objects.filter(origem='MIGRACAO_EPI_UN_20260820').order_by('-pk')
    for historico in historicos.iterator():
        Insumo.objects.filter(pk=historico.insumo_id).update(
            unidade_medida=historico.valor_anterior
        )
    historicos.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0031_inventario_lider_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistdiario',
            options={'permissions': [('visualizar_checklists', 'Pode visualizar checklists'), ('gerenciar_checklists', 'Pode gerenciar checklists'), ('preencher_checklists', 'Pode preencher checklists'), ('finalizar_checklists', 'Pode finalizar checklists'), ('reabrir_checklists', 'Pode reabrir checklists'), ('imprimir_checklists', 'Pode imprimir checklists'), ('visualizar_historico_checklists', 'Pode visualizar históricos de checklists')]},
        ),
        migrations.CreateModel(
            name='ChecklistEquipamentoQuantidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Sistema', 'Sistema'), ('Coletores', 'Coletores'), ('Notebooks', 'Notebooks'), ('Impressoras', 'Impressoras'), ('Routers', 'Routers')], max_length=50)),
                ('quantidade_enviada', models.PositiveIntegerField()),
                ('quantidade_identificada', models.PositiveIntegerField(default=0)),
                ('quantidade_retornada', models.PositiveIntegerField(default=0)),
                ('status_retorno', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFERIDO', 'Conferido')], default='PENDENTE', max_length=20)),
                ('conferido_em', models.DateTimeField(blank=True, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos_quantitativos', to='insumos.checklistdiario')),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklists_equipamentos_conferidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('checklist', 'categoria'), name='checklist_categoria_equipamento_unica'), models.CheckConstraint(condition=models.Q(('quantidade_identificada__lte', models.F('quantidade_enviada'))), name='checklist_equip_identificados_lte_enviados'), models.CheckConstraint(condition=models.Q(('quantidade_retornada__lte', models.F('quantidade_enviada'))), name='checklist_equip_retornados_lte_enviados')],
            },
        ),
        migrations.RunPython(padronizar_epis_como_unidade, reverter_padronizacao_epis),
    ]
