# Generated by Django 5.2.6 on 2026-08-26 01:55

import django.core.validators
import django.db.models.deletion
import insumos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0033_documentacao_relatorios_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteChecklistDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(storage=insumos.models.checklist_cliente_storage, upload_to=insumos.models.checklist_cliente_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'], message='Envie um arquivo PDF ou Word (.pdf, .doc ou .docx).')])),
                ('nome_original', models.CharField(max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_documento', to='insumos.cliente')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklists_clientes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'arquivo de checklist do cliente',
                'verbose_name_plural': 'arquivos de checklist dos clientes',
            },
        ),
    ]
