# Generated by Django 5.2.17 on 2026-09-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0037_checklist_documento_por_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistequipamentoquantidade',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
    ]
