# Generated by Django 5.2.6 on 2026-07-15 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0029_alter_equipamento_status_inativo'),
        ('insumos', '0020_limite_estoque_minimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPlanningSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('RUNNING', 'Executando'), ('SUCCESS', 'Sucesso'), ('FAILED', 'Falha')], default='RUNNING', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('received', models.PositiveIntegerField(default=0)),
                ('created', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('missing', models.PositiveIntegerField(default=0)),
                ('materialized', models.PositiveIntegerField(default=0)),
                ('pending_materialization', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['endpoint', 'started_at'], name='plan_sync_endpoint_date'), models.Index(fields=['status', 'started_at'], name='plan_sync_status_date')],
            },
        ),
        migrations.CreateModel(
            name='PlanningClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('data_source', models.CharField(default='INVENTORY_PLANNING', editable=False, max_length=40)),
                ('synced_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('external_created_at', models.DateTimeField(blank=True, null=True)),
                ('external_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_state', models.CharField(choices=[('PRESENT', 'Presente'), ('MISSING', 'Ausente na fonte')], db_index=True, default='PRESENT', max_length=16)),
                ('corporate_name', models.CharField(blank=True, default='', max_length=255)),
                ('trade_name', models.CharField(blank=True, default='', max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=80)),
                ('segment_external_id', models.CharField(blank=True, default='', max_length=128)),
                ('segment_name', models.CharField(blank=True, default='', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('trade_name', 'corporate_name'),
                'constraints': [models.UniqueConstraint(fields=('data_source', 'external_id'), name='uniq_plan_client_source_id')],
            },
        ),
        migrations.CreateModel(
            name='PlanningClientBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_client_bindings_confirmed', to=settings.AUTH_USER_MODEL)),
                ('local_client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='planning_binding', to='insumos.cliente')),
                ('planning_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_binding', to='integracao.planningclient')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('data_source', models.CharField(default='INVENTORY_PLANNING', editable=False, max_length=40)),
                ('synced_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('external_created_at', models.DateTimeField(blank=True, null=True)),
                ('external_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_state', models.CharField(choices=[('PRESENT', 'Presente'), ('MISSING', 'Ausente na fonte')], db_index=True, default='PRESENT', max_length=16)),
                ('status', models.CharField(db_index=True, max_length=24)),
                ('planned_at', models.DateTimeField(db_index=True)),
                ('planned_pieces', models.PositiveBigIntegerField(blank=True, null=True)),
                ('planned_headcount', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('parent_external_id', models.CharField(blank=True, default='', max_length=128)),
                ('import_data', models.JSONField(blank=True, default=dict)),
                ('import_key', models.CharField(blank=True, default='', max_length=255)),
                ('import_revision', models.CharField(blank=True, default='', max_length=120)),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('meeting_point_external_id', models.CharField(blank=True, default='', max_length=128)),
                ('meeting_point_name', models.CharField(blank=True, default='', max_length=255)),
                ('sensitive_data_filtered', models.BooleanField(default=False)),
                ('source_payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('materialization_status', models.CharField(choices=[('PENDING', 'Pendente de vínculos'), ('MATERIALIZED', 'Inventário criado'), ('NOT_APPLICABLE', 'Evento FILHO'), ('ERROR', 'Erro de materialização')], db_index=True, default='PENDING', max_length=20)),
                ('materialization_error', models.CharField(blank=True, default='', max_length=255)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='integracao.planningclient')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='integracao.planningevent')),
            ],
            options={
                'ordering': ('planned_at', 'external_id'),
            },
        ),
        migrations.CreateModel(
            name='InventoryPlanningEventBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='planning_event_binding', to='insumos.inventario')),
                ('planning_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_binding', to='integracao.planningevent')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningInventoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('data_source', models.CharField(default='INVENTORY_PLANNING', editable=False, max_length=40)),
                ('synced_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('external_created_at', models.DateTimeField(blank=True, null=True)),
                ('external_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_state', models.CharField(choices=[('PRESENT', 'Presente'), ('MISSING', 'Ausente na fonte')], db_index=True, default='PRESENT', max_length=16)),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(blank=True, default='', max_length=80)),
                ('kind', models.CharField(choices=[('PAI', 'PAI'), ('FILHO', 'FILHO')], max_length=8)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('kind', 'name'),
                'constraints': [models.UniqueConstraint(fields=('data_source', 'external_id'), name='uniq_plan_type_source_id')],
            },
        ),
        migrations.AddField(
            model_name='planningevent',
            name='inventory_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='integracao.planninginventorytype'),
        ),
        migrations.CreateModel(
            name='PlanningRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('data_source', models.CharField(default='INVENTORY_PLANNING', editable=False, max_length=40)),
                ('synced_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('external_created_at', models.DateTimeField(blank=True, null=True)),
                ('external_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_state', models.CharField(choices=[('PRESENT', 'Presente'), ('MISSING', 'Ausente na fonte')], db_index=True, default='PRESENT', max_length=16)),
                ('name', models.CharField(max_length=160)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('data_source', 'external_id'), name='uniq_plan_region_source_id')],
            },
        ),
        migrations.AddField(
            model_name='planningevent',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='integracao.planningregion'),
        ),
        migrations.CreateModel(
            name='PlanningRegionBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_region_bindings_confirmed', to=settings.AUTH_USER_MODEL)),
                ('local_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_region_bindings', to='estoque.base')),
                ('planning_region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_binding', to='integracao.planningregion')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('data_source', models.CharField(default='INVENTORY_PLANNING', editable=False, max_length=40)),
                ('synced_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('external_created_at', models.DateTimeField(blank=True, null=True)),
                ('external_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_state', models.CharField(choices=[('PRESENT', 'Presente'), ('MISSING', 'Ausente na fonte')], db_index=True, default='PRESENT', max_length=16)),
                ('code', models.CharField(blank=True, default='', max_length=100)),
                ('store_number', models.CharField(blank=True, default='', max_length=80)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('nickname', models.CharField(blank=True, default='', max_length=255)),
                ('corporate_document', models.CharField(blank=True, default='', max_length=32)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('district', models.CharField(blank=True, default='', max_length=120)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='integracao.planningclient')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='integracao.planningregion')),
            ],
            options={
                'ordering': ('code', 'name'),
            },
        ),
        migrations.AddField(
            model_name='planningevent',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='integracao.planningstore'),
        ),
        migrations.AddIndex(
            model_name='planningstore',
            index=models.Index(fields=['client', 'code'], name='plan_store_client_code'),
        ),
        migrations.AddIndex(
            model_name='planningstore',
            index=models.Index(fields=['region', 'store_number'], name='plan_store_region_num'),
        ),
        migrations.AddConstraint(
            model_name='planningstore',
            constraint=models.UniqueConstraint(fields=('data_source', 'external_id'), name='uniq_plan_store_source_id'),
        ),
        migrations.AddIndex(
            model_name='planningevent',
            index=models.Index(fields=['planned_at', 'status'], name='plan_event_date_status'),
        ),
        migrations.AddIndex(
            model_name='planningevent',
            index=models.Index(fields=['region', 'planned_at'], name='plan_event_region_date'),
        ),
        migrations.AddIndex(
            model_name='planningevent',
            index=models.Index(fields=['parent', 'planned_at'], name='plan_event_parent_date'),
        ),
        migrations.AddConstraint(
            model_name='planningevent',
            constraint=models.UniqueConstraint(fields=('data_source', 'external_id'), name='uniq_plan_event_source_id'),
        ),
    ]
