# Generated by Django 5.2.6 on 2026-07-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryplanningsyncrun',
            name='rate_limit_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryplanningsyncrun',
            name='rate_limit_remaining',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryplanningsyncrun',
            name='rate_limit_reset',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='inventoryplanningsyncrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'RUNNING')), fields=('endpoint',), name='uniq_running_plan_sync_endpoint'),
        ),
    ]
