# Generated by Django 5.2.6 on 2026-07-15 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0029_alter_equipamento_status_inativo'),
        ('insumos', '0020_limite_estoque_minimo'),
        ('integracao', '0002_inventoryplanningsyncrun_rate_limit_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planningclientbinding',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planningclientbinding',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SUGGESTED', 'Sugerido'), ('RULE', 'Regra confirmada')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='planningclientbinding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='planningregionbinding',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planningregionbinding',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SUGGESTED', 'Sugerido'), ('RULE', 'Regra confirmada')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='planningregionbinding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventoryplanningsyncrun',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Executando'), ('SUCCESS', 'Sucesso'), ('FAILED', 'Falha'), ('STALE', 'Abandonada')], default='RUNNING', max_length=16),
        ),
        migrations.AlterField(
            model_name='planningclientbinding',
            name='local_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_bindings', to='insumos.cliente'),
        ),
        migrations.AlterField(
            model_name='planningevent',
            name='materialization_status',
            field=models.CharField(choices=[('PENDING', 'Pendente de vínculos'), ('MATERIALIZED', 'Inventário criado'), ('NOT_APPLICABLE', 'Evento FILHO'), ('SKIPPED', 'Não criado pelo status externo'), ('ERROR', 'Erro de materialização')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='PlanningOperationalBaseBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('SUGGESTED', 'Sugerido'), ('RULE', 'Regra confirmada')], default='MANUAL', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_operational_bindings_confirmed', to=settings.AUTH_USER_MODEL)),
                ('local_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_operational_bindings', to='estoque.base')),
                ('planning_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_base_bindings', to='integracao.planningclient')),
                ('planning_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_base_bindings', to='integracao.planningregion')),
            ],
            options={
                'permissions': [('gerenciar_mapeamentos_planning', 'Pode gerenciar mapeamentos do planejamento'), ('executar_materializacao_planning', 'Pode executar materialização do planejamento')],
                'indexes': [models.Index(fields=['local_base', 'is_active'], name='plan_op_base_active')],
                'constraints': [models.UniqueConstraint(fields=('planning_client', 'planning_region'), name='uniq_planning_client_region_binding')],
            },
        ),
    ]
