# Generated by Django 5.2.6 on 2026-08-04 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0031_perfil_whatsapp_ativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_em', models.DateTimeField()),
                ('fim_em', models.DateTimeField()),
                ('status', models.CharField(choices=[('NAO_INICIADA', 'Não iniciada'), ('DISPONIVEL', 'Disponível'), ('EM_ANDAMENTO', 'Em andamento'), ('ENVIADA', 'Enviada para análise'), ('COM_DIVERGENCIAS', 'Com divergências'), ('EM_REGULARIZACAO', 'Em regularização'), ('FINALIZADA', 'Finalizada'), ('REABERTA', 'Reaberta'), ('EXPIRADA', 'Expirada'), ('DISPENSADA', 'Dispensada')], db_index=True, default='NAO_INICIADA', max_length=25)),
                ('snapshot_criado_em', models.DateTimeField(blank=True, null=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('versao_reabertura', models.PositiveIntegerField(default=0)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='estoque.base')),
                ('enviada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_enviadas', to=settings.AUTH_USER_MODEL)),
                ('finalizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_finalizadas', to=settings.AUTH_USER_MODEL)),
                ('iniciada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_iniciadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaDivergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('OUTRA_BASE', 'Encontrado em outra base'), ('NAO_LOCALIZADO', 'Não localizado'), ('NAO_CADASTRADO', 'Não cadastrado'), ('IDENTIFICADOR_DUPLICADO', 'Identificador duplicado'), ('STATUS_INCOMPATIVEL', 'Status incompatível'), ('CONFLITO_TRANSFERENCIA', 'Conflito com transferência'), ('CONFLITO_EMPRESTIMO', 'Conflito com empréstimo')], db_index=True, max_length=35)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em análise'), ('AGUARDANDO_TRANSFERENCIA', 'Aguardando transferência'), ('RESOLVIDA', 'Resolvida'), ('BLOQUEADA', 'Bloqueada'), ('CANCELADA', 'Cancelada')], db_index=True, default='ABERTA', max_length=35)),
                ('descricao', models.TextField(blank=True)),
                ('motivo_bloqueio', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('resolvida_em', models.DateTimeField(blank=True, null=True)),
                ('auditoria_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divergencias', to='auditorias.auditoriabase')),
                ('base_encontrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estoque.base')),
                ('base_esperada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estoque.base')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='divergencias_auditoria', to='estoque.equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_index=True, max_length=60)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('auditoria_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='auditorias.auditoriabase')),
                ('divergencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='auditorias.auditoriadivergencia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criado_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_informado', models.CharField(db_index=True, max_length=180)),
                ('valor_normalizado', models.CharField(db_index=True, max_length=180)),
                ('tipo_identificador', models.CharField(choices=[('PATRIMONIO', 'Patrimônio'), ('SERIE', 'Número de série'), ('CODIGO', 'Código interno'), ('DESCONHECIDO', 'Não identificado')], max_length=20)),
                ('origem', models.CharField(choices=[('LEITOR', 'Leitor'), ('MANUAL', 'Digitação manual'), ('PLANILHA', 'Importação de planilha')], default='MANUAL', max_length=20)),
                ('classificacao', models.CharField(choices=[('CORRETO', 'Localizado na base correta'), ('OUTRA_BASE', 'Localizado em outra base'), ('NAO_CADASTRADO', 'Equipamento não cadastrado'), ('IDENTIFICADOR_DUPLICADO', 'Identificador duplicado'), ('LEITURA_DUPLICADA', 'Leitura duplicada'), ('EM_TRANSFERENCIA', 'Em transferência'), ('EMPRESTADO', 'Emprestado'), ('STATUS_INCOMPATIVEL', 'Status incompatível')], db_index=True, max_length=30)),
                ('lida_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cancelada', models.BooleanField(db_index=True, default=False)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('dados_classificacao', models.JSONField(blank=True, default=dict)),
                ('auditoria_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='auditorias.auditoriabase')),
                ('base_encontrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estoque.base')),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leituras_auditoria', to='estoque.equipamento')),
                ('lida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leituras_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auditoriadivergencia',
            name='leitura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='divergencias', to='auditorias.auditorialeitura'),
        ),
        migrations.CreateModel(
            name='AuditoriaResolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MANTER_NA_BASE', 'Manter na base atual'), ('TRANSFERIR', 'Transferir equipamento'), ('AJUSTE_ADMINISTRATIVO', 'Ajuste administrativo'), ('SEM_ACAO', 'Sem alteração')], max_length=30)),
                ('justificativa', models.TextField()),
                ('resolvida_em', models.DateTimeField(auto_now_add=True)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('base_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estoque.base')),
                ('divergencia', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resolucao', to='auditorias.auditoriadivergencia')),
                ('nova_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estoque.base')),
                ('resolvida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolucoes_auditoria', to=settings.AUTH_USER_MODEL)),
                ('transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolucoes_auditoria', to='estoque.transferencia')),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaSnapshotEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_id_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),
                ('produto_descricao', models.CharField(blank=True, max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('patrimonio', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('tipo_uso', models.CharField(blank=True, max_length=30)),
                ('responsavel', models.CharField(blank=True, max_length=150)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('auditoria_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_equipamentos', to='auditorias.auditoriabase')),
                ('base_esperada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estoque.base')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots_auditoria', to='estoque.equipamento')),
            ],
        ),
        migrations.AddField(
            model_name='auditoriadivergencia',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='divergencias', to='auditorias.auditoriasnapshotequipamento'),
        ),
        migrations.CreateModel(
            name='CampanhaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('instrucoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em andamento'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada')], db_index=True, default='RASCUNHO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanhas_auditoria_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanhas_auditoria', to='estoque.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='auditoriabase',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_bases', to='auditorias.campanhaauditoria'),
        ),
        migrations.AddIndex(
            model_name='auditorialeitura',
            index=models.Index(fields=['auditoria_base', 'valor_normalizado'], name='auditorias__auditor_5f9b68_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialeitura',
            index=models.Index(fields=['auditoria_base', 'equipamento', 'cancelada'], name='auditorias__auditor_c665ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditoriasnapshotequipamento',
            constraint=models.UniqueConstraint(fields=('auditoria_base', 'equipamento'), name='uq_snapshot_auditoria_equipamento'),
        ),
        migrations.AddIndex(
            model_name='auditoriadivergencia',
            index=models.Index(fields=['auditoria_base', 'status', 'tipo'], name='auditorias__auditor_13f0cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditoriadivergencia',
            constraint=models.UniqueConstraint(condition=models.Q(('snapshot__isnull', False)), fields=('auditoria_base', 'snapshot', 'tipo'), name='uq_divergencia_snapshot_tipo'),
        ),
        migrations.AddConstraint(
            model_name='auditoriadivergencia',
            constraint=models.UniqueConstraint(condition=models.Q(('leitura__isnull', False)), fields=('auditoria_base', 'leitura', 'tipo'), name='uq_divergencia_leitura_tipo'),
        ),
        migrations.AddIndex(
            model_name='auditoriabase',
            index=models.Index(fields=['status', 'inicio_em', 'fim_em'], name='auditorias__status_47ae2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditoriabase',
            constraint=models.UniqueConstraint(fields=('campanha', 'base'), name='uq_auditoria_campanha_base'),
        ),
    ]
