DATA_SOURCE_INVENTORY_PLANNING = "INVENTORY_PLANNING"

SENSITIVE_FIELD_TOKENS = {
    "cpf",
    "rg",
    "pis",
    "pix",
    "email",
    "phone",
    "telefone",
    "mobile",
    "celular",
    "bankaccount",
    "bankaccounts",
    "bank",
    "dadosbancarios",
    "contabancaria",
    "contasbancarias",
    "agenciabancaria",
    "bankcode",
    "bankname",
    "agencynumber",
    "agencydigit",
    "accountnumber",
    "accountdigit",
    "pixkey",
    "documentcpf",
    "documentrg",
    "pisnumber",
    "foreign_document",
    "foreigndocument",
    "mothername",
    "birthdate",
    "datanascimento",
    "meicnpj",
}
