# Generated by Django 5.2.6 on 2026-08-11 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0034_perfil_bases_escopo_compras_and_more'),
        ('insumos', '0027_alter_movimentacaoinsumo_options_saldoinsumobase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=20)),
                ('ano', models.PositiveSmallIntegerField(db_index=True)),
                ('tipo', models.CharField(choices=[('TRANSFERENCIA', 'Transferência'), ('SICK', 'SICK'), ('EMPRESTIMO', 'Empréstimo'), ('INSUMO', 'Movimentação de insumo'), ('CONSUMO', 'Consumo'), ('MANUTENCAO', 'Manutenção'), ('OUTRO', 'Outro')], db_index=True, max_length=20)),
                ('prioridade', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente'), ('EMERGENCIAL', 'Emergencial')], default='NORMAL', max_length=15)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGUARDANDO_AUTORIZACAO', 'Aguardando autorização'), ('AUTORIZADA', 'Autorizada'), ('EM_EXECUCAO', 'Em execução'), ('AGUARDANDO_CONFIRMACAO', 'Aguardando confirmação'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='AGUARDANDO_AUTORIZACAO', max_length=30)),
                ('motivo', models.TextField()),
                ('descricao', models.TextField(blank=True)),
                ('justificativa_urgencia', models.TextField(blank=True)),
                ('prazo_em', models.DateTimeField(blank=True, null=True)),
                ('aberto_em', models.DateTimeField(auto_now_add=True)),
                ('autorizado_em', models.DateTimeField(blank=True, null=True)),
                ('executado_em', models.DateTimeField(blank=True, null=True)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('chamado_referencia', models.CharField(blank=True, max_length=80)),
                ('autorizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('base_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico_destino', to='estoque.base')),
                ('base_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico_origem', to='estoque.base')),
                ('base_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico_responsavel', to='estoque.base')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='estoque.empresa')),
                ('emprestimo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordem_servico', to='estoque.emprestimo')),
                ('movimentacao_insumo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordem_servico', to='insumos.movimentacaoinsumo')),
                ('recebedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico_recebidas', to=settings.AUTH_USER_MODEL)),
                ('responsavel_operacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico_responsavel_operacional', to=settings.AUTH_USER_MODEL)),
                ('sick', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordem_servico', to='estoque.sick')),
                ('solicitacao_insumo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordem_servico', to='insumos.solicitacaoinsumo')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('transferencia', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordem_servico', to='estoque.transferencia')),
            ],
            options={
                'ordering': ['-aberto_em', '-id'],
                'permissions': [('autorizar_ordem_servico', 'Pode autorizar ordem de serviço'), ('visualizar_todas_ordens_servico', 'Pode visualizar todas as ordens de serviço')],
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='ordens_servico/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('hash_arquivo', models.CharField(max_length=64)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='ordens_servico.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServicoAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUTORIZACAO', 'Autorização'), ('EXECUCAO', 'Execução'), ('RECEBIMENTO', 'Recebimento'), ('ENCERRAMENTO', 'Encerramento')], max_length=20)),
                ('assinado_em', models.DateTimeField(auto_now_add=True)),
                ('hash_documento', models.CharField(max_length=64)),
                ('versao_documento', models.PositiveIntegerField(default=1)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='ordens_servico.ordemservico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServicoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_index=True, max_length=60)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='ordens_servico.ordemservico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criado_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natureza', models.CharField(choices=[('EQUIPAMENTO', 'Equipamento'), ('INSUMO_TRANSFERIDO', 'Insumo transferido'), ('INSUMO_CONSUMIDO', 'Insumo consumido'), ('PECA', 'Peça de manutenção'), ('DEVOLUCAO', 'Item devolvido'), ('PERDA_AVARIA', 'Perda ou avaria')], max_length=25)),
                ('descricao', models.CharField(max_length=255)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('unidade', models.CharField(blank=True, max_length=30)),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=14)),
                ('lote', models.CharField(blank=True, max_length=100)),
                ('validade', models.DateField(blank=True, null=True)),
                ('patrimonio', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=150)),
                ('origem', models.CharField(blank=True, max_length=150)),
                ('destino', models.CharField(blank=True, max_length=150)),
                ('condicao_saida', models.CharField(blank=True, max_length=120)),
                ('condicao_retorno', models.CharField(blank=True, max_length=120)),
                ('custo_unitario_historico', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('dados_snapshot', models.JSONField(blank=True, default=dict)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.equipamento')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insumos.insumo')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='ordens_servico.ordemservico')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SequenciaOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.empresa')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ordemservico',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='os_numero_empresa_unico'),
        ),
        migrations.AddConstraint(
            model_name='ordemservico',
            constraint=models.CheckConstraint(condition=models.Q(('prioridade', 'NORMAL'), models.Q(('justificativa_urgencia', ''), _negated=True), _connector='OR'), name='os_urgencia_exige_justificativa'),
        ),
        migrations.AddConstraint(
            model_name='ordemservicoassinatura',
            constraint=models.UniqueConstraint(fields=('ordem', 'tipo'), name='os_assinatura_tipo_unica'),
        ),
        migrations.AddConstraint(
            model_name='ordemservicolinha',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='os_linha_quantidade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='sequenciaordemservico',
            constraint=models.UniqueConstraint(fields=('empresa', 'ano'), name='os_sequencia_empresa_ano_unica'),
        ),
    ]
