"""
Django settings for estoque_django project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'unsafe-key')

# O runserver precisa do modo de desenvolvimento para servir os arquivos
# encontrados pelos staticfiles. Em produção, defina DEBUG=False no ambiente.
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['.onrender.com', 'localhost', '127.0.0.1']

LOGIN_URL = 'estoque:login'
LOGIN_REDIRECT_URL = 'estoque:index'
LOGOUT_REDIRECT_URL = 'estoque:login'

#Database
import dj_database_url

DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'estoque_render_dump'),
            'USER': os.getenv('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'admininventory'),
            'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'estoque.apps.EstoqueConfig',
    'auditorias.apps.AuditoriasConfig',
    'core',
    'insumos',
    'integracao.apps.IntegracaoConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'estoque.middleware.UserLanguageMiddleware',
    'estoque.middleware.EmpresaMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'estoque_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [

                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'insumos.context_processors.menu_insumos',
                'estoque.context_processors.notificacoes_context',
                'estoque.context_processors.permissoes_especiais',

            ],
        },
    },
]

WSGI_APPLICATION = 'estoque_django.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('pt-br', 'Português'),
    ('es', 'Español'),
    ('en', 'English'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Inventory Planning API. A URL é validada novamente pelo cliente antes de
# qualquer requisição para impedir o envio da chave por HTTP.
INVENTORY_PLANNING_API_URL = os.getenv('INVENTORY_PLANNING_API_URL', '')
INVENTORY_PLANNING_API_KEY = os.getenv('INVENTORY_PLANNING_API_KEY', '')
INVENTORY_PLANNING_TIMEOUT = float(os.getenv('INVENTORY_PLANNING_TIMEOUT', '15'))
INVENTORY_PLANNING_MAX_RETRIES = int(os.getenv('INVENTORY_PLANNING_MAX_RETRIES', '4'))
INVENTORY_PLANNING_BACKOFF_BASE = float(os.getenv('INVENTORY_PLANNING_BACKOFF_BASE', '1'))
INVENTORY_PLANNING_CATALOG_CACHE_TTL = int(
    os.getenv('INVENTORY_PLANNING_CATALOG_CACHE_TTL', '21600')
)
INVENTORY_PLANNING_SYSTEM_USERNAME = os.getenv(
    'INVENTORY_PLANNING_SYSTEM_USERNAME',
    'inventory_planning_sync',
)

# Leitura autenticada e somente-leitura da tela de inventários em tempo real.
INVENTORY_PORTAL_ENABLED = os.getenv('INVENTORY_PORTAL_ENABLED', 'False').lower() == 'true'
INVENTORY_PORTAL_URL = os.getenv(
    'INVENTORY_PORTAL_URL',
    'https://novoportal.inventorybrasil.com.br/',
)
INVENTORY_PORTAL_USERNAME = os.getenv('INVENTORY_PORTAL_USERNAME', '')
INVENTORY_PORTAL_PASSWORD = os.getenv('INVENTORY_PORTAL_PASSWORD', '')
INVENTORY_PORTAL_TIMEOUT = float(os.getenv('INVENTORY_PORTAL_TIMEOUT', '20'))
INVENTORY_PORTAL_MAX_RANGE_DAYS = int(os.getenv('INVENTORY_PORTAL_MAX_RANGE_DAYS', '31'))
INVENTORY_PORTAL_MAX_DETAIL_RECORDS = int(os.getenv('INVENTORY_PORTAL_MAX_DETAIL_RECORDS', '20'))

# Interpretação opcional de linguagem natural. O LLM não acessa ferramentas nem
# dados do Portal; ele retorna apenas filtros estruturados validados pelo Django.
TORY_LLM_ENABLED = os.getenv('TORY_LLM_ENABLED', 'False').lower() == 'true'
TORY_LLM_MODEL = os.getenv('TORY_LLM_MODEL', 'gpt-5.6-sol')
TORY_LLM_TIMEOUT = float(os.getenv('TORY_LLM_TIMEOUT', '20'))
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')

# Entregas opcionais por WhatsApp. Permanecem desabilitadas por padrão.
WHATSAPP_ENABLED = os.getenv('WHATSAPP_ENABLED', 'False').lower() == 'true'
WHATSAPP_PROVIDER = os.getenv('WHATSAPP_PROVIDER', 'disabled')
WHATSAPP_API_BASE_URL = os.getenv('WHATSAPP_API_BASE_URL', '')
WHATSAPP_ACCESS_TOKEN = os.getenv('WHATSAPP_ACCESS_TOKEN', '')
WHATSAPP_PHONE_NUMBER_ID = os.getenv('WHATSAPP_PHONE_NUMBER_ID', '')
WHATSAPP_BUSINESS_ACCOUNT_ID = os.getenv('WHATSAPP_BUSINESS_ACCOUNT_ID', '')
WHATSAPP_WEBHOOK_VERIFY_TOKEN = os.getenv('WHATSAPP_WEBHOOK_VERIFY_TOKEN', '')
WHATSAPP_WEBHOOK_APP_SECRET = os.getenv('WHATSAPP_WEBHOOK_APP_SECRET', '')
WHATSAPP_DEFAULT_COUNTRY_CODE = os.getenv('WHATSAPP_DEFAULT_COUNTRY_CODE', '55')
WHATSAPP_TIMEOUT = float(os.getenv('WHATSAPP_TIMEOUT', '10'))
WHATSAPP_MAX_RETRIES = int(os.getenv('WHATSAPP_MAX_RETRIES', '5'))
WHATSAPP_RETRY_BASE_SECONDS = int(os.getenv('WHATSAPP_RETRY_BASE_SECONDS', '60'))

# Pesquisa manual de preços nos fornecedores utilizados pela empresa.
ONLINE_PRICE_SEARCH_TIMEOUT = float(os.getenv('ONLINE_PRICE_SEARCH_TIMEOUT', '15'))
GIMBA_PRICE_SEARCH_ENABLED = os.getenv(
    'GIMBA_PRICE_SEARCH_ENABLED', 'True'
).lower() == 'true'
FIDELITY_PRICE_SEARCH_ENABLED = os.getenv(
    'FIDELITY_PRICE_SEARCH_ENABLED', 'True'
).lower() == 'true'

CACHES = {
    'default': {
        'BACKEND': os.getenv(
            'DJANGO_CACHE_BACKEND',
            'django.core.cache.backends.locmem.LocMemCache',
        ),
        'LOCATION': os.getenv('DJANGO_CACHE_LOCATION', 'gerenciador-estoque'),
        'TIMEOUT': INVENTORY_PLANNING_CATALOG_CACHE_TTL,
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'integracao.inventory_planning': {
            'handlers': ['console'],
            'level': os.getenv('INVENTORY_PLANNING_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'integracao.inventory_portal': {
            'handlers': ['console'],
            'level': os.getenv('INVENTORY_PORTAL_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'integracao.tory_llm': {
            'handlers': ['console'],
            'level': os.getenv('TORY_LLM_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

# Configurações CSRF
#CSRF_COOKIE_SECURE = False
#CSRF_COOKIE_HTTPONLY = False
#CSRF_USE_SESSIONS = False
#CSRF_COOKIE_NAME = 'csrftoken'
CSRF_TRUSTED_ORIGINS = [
    "https://gerenciadorestoque.onrender.com",
]
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    (
        'django.core.mail.backends.console.EmailBackend'
        if DEBUG
        else 'django.core.mail.backends.smtp.EmailBackend'
    ),
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL',
    EMAIL_HOST_USER or 'nao-responda@inventory.local',
)

MEDIA_URL = '/media/'
MEDIA_ROOT = '/var/data/media'

import os

os.makedirs(MEDIA_ROOT, exist_ok=True)
