"""
Django settings for estoque_django project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured


def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in {
        '1', 'true', 'yes', 'on',
    }


def env_list(name, default=''):
    return [item.strip() for item in os.getenv(name, default).split(',') if item.strip()]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

ENVIRONMENT = os.getenv('DJANGO_ENVIRONMENT', 'development').strip().lower()
DEBUG = env_bool('DEBUG', ENVIRONMENT == 'development')

SECRET_KEY = os.getenv('SECRET_KEY', '').strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-development-only-key'
    else:
        raise ImproperlyConfigured('SECRET_KEY deve ser configurada fora do modo de desenvolvimento.')

ALLOWED_HOSTS = env_list(
    'ALLOWED_HOSTS',
    'localhost,127.0.0.1,[::1]' if DEBUG else '',
)
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('ALLOWED_HOSTS deve ser configurado em produção.')

LOGIN_URL = 'estoque:login'
LOGIN_REDIRECT_URL = 'estoque:index'
LOGOUT_REDIRECT_URL = 'estoque:login'

#Database
import dj_database_url

DATABASE_URL = os.getenv('DATABASE_URL', '').strip()
DATABASE_CONN_MAX_AGE = int(os.getenv('DATABASE_CONN_MAX_AGE', '600'))
DATABASE_HEALTH_CHECKS = env_bool('DATABASE_HEALTH_CHECKS', True)
DATABASE_SSL_REQUIRED = env_bool('DATABASE_SSL_REQUIRED', not DEBUG)

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=DATABASE_CONN_MAX_AGE,
            conn_health_checks=DATABASE_HEALTH_CHECKS,
        )
    }
else:
    if not DEBUG:
        raise ImproperlyConfigured('DATABASE_URL deve ser configurada em produção.')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'estoque_render_dump'),
            'USER': os.getenv('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
            'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
            'CONN_MAX_AGE': DATABASE_CONN_MAX_AGE,
            'CONN_HEALTH_CHECKS': DATABASE_HEALTH_CHECKS,
        }
    }

if DATABASE_SSL_REQUIRED and DATABASES['default']['ENGINE'] != 'django.db.backends.sqlite3':
    DATABASES['default'].setdefault('OPTIONS', {}).setdefault('sslmode', 'require')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'estoque.apps.EstoqueConfig',
    'auditorias.apps.AuditoriasConfig',
    'core',
    'insumos',
    'integracao.apps.IntegracaoConfig',
    'ordens_servico.apps.OrdensServicoConfig',
    'compras.apps.ComprasConfig',
    'chamados.apps.ChamadosConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'estoque.middleware.UserLanguageMiddleware',
    'estoque.middleware.EmpresaMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'estoque_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [

                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'insumos.context_processors.menu_insumos',
                'estoque.context_processors.notificacoes_context',
                'estoque.context_processors.permissoes_especiais',

            ],
        },
    },
]

WSGI_APPLICATION = 'estoque_django.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('pt-br', 'Português'),
    ('es', 'Español'),
    ('en', 'English'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.getenv('MEDIA_ROOT') or BASE_DIR / 'media')

USE_S3 = env_bool('USE_S3', False)
STORAGES = {
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

if USE_S3:
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', '').strip()
    if not AWS_STORAGE_BUCKET_NAME:
        raise ImproperlyConfigured('AWS_STORAGE_BUCKET_NAME deve ser configurado quando USE_S3=True.')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'sa-east-1')
    AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL') or None
    AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN') or None
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_OBJECT_PARAMETERS = {'ServerSideEncryption': 'AES256'}
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'bucket_name': AWS_STORAGE_BUCKET_NAME,
            'region_name': AWS_S3_REGION_NAME,
            'endpoint_url': AWS_S3_ENDPOINT_URL,
            'custom_domain': AWS_S3_CUSTOM_DOMAIN,
            'default_acl': None,
            'querystring_auth': True,
            'file_overwrite': False,
            'object_parameters': AWS_S3_OBJECT_PARAMETERS,
        },
    }
else:
    STORAGES['default'] = {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Inventory Planning API. A URL é validada novamente pelo cliente antes de
# qualquer requisição para impedir o envio da chave por HTTP.
INVENTORY_PLANNING_API_URL = os.getenv('INVENTORY_PLANNING_API_URL', '')
INVENTORY_PLANNING_API_KEY = os.getenv('INVENTORY_PLANNING_API_KEY', '')
INVENTORY_PLANNING_TIMEOUT = float(os.getenv('INVENTORY_PLANNING_TIMEOUT', '15'))
INVENTORY_PLANNING_MAX_RETRIES = int(os.getenv('INVENTORY_PLANNING_MAX_RETRIES', '4'))
INVENTORY_PLANNING_BACKOFF_BASE = float(os.getenv('INVENTORY_PLANNING_BACKOFF_BASE', '1'))
INVENTORY_PLANNING_CATALOG_CACHE_TTL = int(
    os.getenv('INVENTORY_PLANNING_CATALOG_CACHE_TTL', '21600')
)
INVENTORY_PLANNING_SYSTEM_USERNAME = os.getenv(
    'INVENTORY_PLANNING_SYSTEM_USERNAME',
    'inventory_planning_sync',
)

# Leitura autenticada e somente-leitura da tela de inventários em tempo real.
INVENTORY_PORTAL_ENABLED = os.getenv('INVENTORY_PORTAL_ENABLED', 'False').lower() == 'true'
INVENTORY_PORTAL_URL = os.getenv(
    'INVENTORY_PORTAL_URL',
    'https://novoportal.inventorybrasil.com.br/',
)
INVENTORY_PORTAL_USERNAME = os.getenv('INVENTORY_PORTAL_USERNAME', '')
INVENTORY_PORTAL_PASSWORD = os.getenv('INVENTORY_PORTAL_PASSWORD', '')
INVENTORY_PORTAL_TIMEOUT = float(os.getenv('INVENTORY_PORTAL_TIMEOUT', '20'))
INVENTORY_PORTAL_MAX_RANGE_DAYS = int(os.getenv('INVENTORY_PORTAL_MAX_RANGE_DAYS', '31'))
INVENTORY_PORTAL_MAX_DETAIL_RECORDS = int(os.getenv('INVENTORY_PORTAL_MAX_DETAIL_RECORDS', '20'))

# Interpretação opcional de linguagem natural. O LLM não acessa ferramentas nem
# dados do Portal; ele retorna apenas filtros estruturados validados pelo Django.
TORY_LLM_ENABLED = os.getenv('TORY_LLM_ENABLED', 'False').lower() == 'true'
TORY_LLM_MODEL = os.getenv('TORY_LLM_MODEL', 'gpt-5.6-sol')
TORY_LLM_TIMEOUT = float(os.getenv('TORY_LLM_TIMEOUT', '20'))
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')

# Entregas opcionais por WhatsApp. Permanecem desabilitadas por padrão.
WHATSAPP_ENABLED = os.getenv('WHATSAPP_ENABLED', 'False').lower() == 'true'
WHATSAPP_PROVIDER = os.getenv('WHATSAPP_PROVIDER', 'disabled')
WHATSAPP_API_BASE_URL = os.getenv('WHATSAPP_API_BASE_URL', '')
WHATSAPP_ACCESS_TOKEN = os.getenv('WHATSAPP_ACCESS_TOKEN', '')
WHATSAPP_PHONE_NUMBER_ID = os.getenv('WHATSAPP_PHONE_NUMBER_ID', '')
WHATSAPP_BUSINESS_ACCOUNT_ID = os.getenv('WHATSAPP_BUSINESS_ACCOUNT_ID', '')
WHATSAPP_WEBHOOK_VERIFY_TOKEN = os.getenv('WHATSAPP_WEBHOOK_VERIFY_TOKEN', '')
WHATSAPP_WEBHOOK_APP_SECRET = os.getenv('WHATSAPP_WEBHOOK_APP_SECRET', '')
WHATSAPP_DEFAULT_COUNTRY_CODE = os.getenv('WHATSAPP_DEFAULT_COUNTRY_CODE', '55')
WHATSAPP_TIMEOUT = float(os.getenv('WHATSAPP_TIMEOUT', '10'))
WHATSAPP_MAX_RETRIES = int(os.getenv('WHATSAPP_MAX_RETRIES', '5'))
WHATSAPP_RETRY_BASE_SECONDS = int(os.getenv('WHATSAPP_RETRY_BASE_SECONDS', '60'))

# Pesquisa manual de preços nos fornecedores utilizados pela empresa.
ONLINE_PRICE_SEARCH_TIMEOUT = float(os.getenv('ONLINE_PRICE_SEARCH_TIMEOUT', '15'))
GIMBA_PRICE_SEARCH_ENABLED = os.getenv(
    'GIMBA_PRICE_SEARCH_ENABLED', 'True'
).lower() == 'true'
FIDELITY_PRICE_SEARCH_ENABLED = os.getenv(
    'FIDELITY_PRICE_SEARCH_ENABLED', 'True'
).lower() == 'true'

CACHES = {
    'default': {
        'BACKEND': os.getenv(
            'DJANGO_CACHE_BACKEND',
            'django.core.cache.backends.locmem.LocMemCache',
        ),
        'LOCATION': os.getenv('DJANGO_CACHE_LOCATION', 'gerenciador-estoque'),
        'TIMEOUT': INVENTORY_PLANNING_CATALOG_CACHE_TTL,
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'integracao.inventory_planning': {
            'handlers': ['console'],
            'level': os.getenv('INVENTORY_PLANNING_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'integracao.inventory_portal': {
            'handlers': ['console'],
            'level': os.getenv('INVENTORY_PORTAL_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'integracao.tory_llm': {
            'handlers': ['console'],
            'level': os.getenv('TORY_LLM_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

# Configurações CSRF
#CSRF_COOKIE_SECURE = False
#CSRF_COOKIE_HTTPONLY = False
#CSRF_USE_SESSIONS = False
#CSRF_COOKIE_NAME = 'csrftoken'
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', not DEBUG)
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', not DEBUG)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', not DEBUG)
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', False)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    (
        'django.core.mail.backends.console.EmailBackend'
        if DEBUG
        else 'django.core.mail.backends.smtp.EmailBackend'
    ),
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL',
    EMAIL_HOST_USER or 'nao-responda@inventory.local',
)
