# Generated by Django 5.2.6 on 2026-08-11 18:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0034_perfil_bases_escopo_compras_and_more'),
        ('insumos', '0027_alter_movimentacaoinsumo_options_saldoinsumobase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aquisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(blank=True, db_index=True, max_length=80)),
                ('chave_nfe', models.CharField(blank=True, db_index=True, max_length=44)),
                ('arquivo_danfe_pdf', models.FileField(blank=True, upload_to='compras/danfe/%Y/%m/')),
                ('arquivo_xml_nfe', models.FileField(blank=True, upload_to='compras/xml/%Y/%m/')),
                ('numero_pedido_compra', models.CharField(blank=True, db_index=True, max_length=80)),
                ('centro_custo', models.CharField(blank=True, max_length=100)),
                ('data_compra', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('APROVADA', 'Aprovada'), ('EM_RECEBIMENTO', 'Em recebimento'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada')], db_index=True, default='RASCUNHO', max_length=20)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aquisicoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aquisicoes_cadastradas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aquisicoes', to='estoque.empresa')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aquisicoes', to='insumos.fornecedorinsumo')),
            ],
            options={
                'ordering': ['-data_compra', '-id'],
                'permissions': [('gerenciar_aquisicoes', 'Pode gerenciar aquisições')],
            },
        ),
        migrations.CreateModel(
            name='CodigoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EAN_GTIN', 'EAN/GTIN'), ('CAIXA', 'Caixa ou pacote'), ('SKU_FABRICANTE', 'SKU do fabricante'), ('INTERNO', 'Código interno')], max_length=25)),
                ('codigo', models.CharField(max_length=100)),
                ('fator_conversao', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_catalogo', to='estoque.empresa')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codigos_catalogo', to='insumos.insumo')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codigos_catalogo', to='estoque.produto')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoValorEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_anterior', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('custo_novo', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('referencia_anterior', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('referencia_nova', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('origem_anterior', models.CharField(blank=True, max_length=30)),
                ('origem_nova', models.CharField(blank=True, max_length=30)),
                ('motivo', models.TextField()),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_valores', to='estoque.equipamento')),
            ],
            options={
                'ordering': ['-alterado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemAquisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('EQUIPAMENTO', 'Equipamento'), ('INSUMO', 'Insumo')], max_length=15)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impostos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacao', models.TextField(blank=True)),
                ('aquisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.aquisicao')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insumos.insumo')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRemessaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_prevista', models.DecimalField(decimal_places=2, default=1, max_digits=14)),
                ('quantidade_recebida', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantidade_avariada', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantidade_faltante', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('custo_unitario_snapshot', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('lote', models.CharField(blank=True, max_length=100)),
                ('validade', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.equipamento')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insumos.insumo')),
                ('item_aquisicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_remessa', to='compras.itemaquisicao')),
            ],
        ),
        migrations.CreateModel(
            name='RecebimentoRemessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField()),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('finaliza_conferencia', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True)),
                ('recebido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinhaRecebimentoRemessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_recebida', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantidade_avariada', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantidade_faltante', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacao', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas_recebimento', to='compras.itemremessacompra')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas', to='compras.recebimentoremessa')),
            ],
        ),
        migrations.CreateModel(
            name='RemessaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(default='', editable=False, max_length=32, unique=True)),
                ('fluxo', models.CharField(choices=[('FORNECEDOR_DIRETO', 'Fornecedor para base'), ('VIA_MATRIZ', 'Fornecedor para matriz'), ('ENTRE_BASES', 'Transferência entre bases')], max_length=25)),
                ('status', models.CharField(choices=[('PREPARADA', 'Preparada'), ('EM_TRANSITO', 'Em trânsito'), ('AGUARDANDO_CONFERENCIA', 'Aguardando conferência'), ('RECEBIDA', 'Recebida'), ('RECEBIDA_PARCIAL', 'Recebida parcialmente'), ('RECEBIDA_DIVERGENCIA', 'Recebida com divergência'), ('CANCELADA', 'Cancelada')], db_index=True, default='PREPARADA', max_length=30)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('previsao_chegada', models.DateField(blank=True, null=True)),
                ('codigo_rastreio', models.CharField(blank=True, max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('aquisicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remessas', to='compras.aquisicao')),
                ('base_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remessas_compra_entrada', to='estoque.base')),
                ('base_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remessas_compra_saida', to='estoque.base')),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remessas_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remessas_compra', to='estoque.empresa')),
                ('enviada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remessas_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('criar_remessa_compra', 'Pode criar remessa de compra'), ('confirmar_remessa_compra', 'Pode confirmar remessa de compra')],
            },
        ),
        migrations.AddField(
            model_name='recebimentoremessa',
            name='remessa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='compras.remessacompra'),
        ),
        migrations.AddField(
            model_name='itemremessacompra',
            name='remessa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.remessacompra'),
        ),
        migrations.CreateModel(
            name='EventoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_index=True, max_length=60)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('aquisicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='compras.aquisicao')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('remessa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='compras.remessacompra')),
            ],
            options={
                'ordering': ['criado_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VinculoEquipamentoAquisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_aquisicao_snapshot', models.DecimalField(decimal_places=4, max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vinculo_aquisicao', to='estoque.equipamento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos_vinculados', to='compras.itemaquisicao')),
            ],
        ),
        migrations.AddConstraint(
            model_name='aquisicao',
            constraint=models.UniqueConstraint(condition=models.Q(('chave_nfe', ''), _negated=True), fields=('empresa', 'chave_nfe'), name='compra_chave_nfe_empresa_unica'),
        ),
        migrations.AddConstraint(
            model_name='codigocatalogo',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo', 'codigo'), name='catalogo_codigo_empresa_unico'),
        ),
        migrations.AddConstraint(
            model_name='codigocatalogo',
            constraint=models.CheckConstraint(condition=models.Q(('fator_conversao__gt', 0)), name='catalogo_fator_positivo'),
        ),
        migrations.AddConstraint(
            model_name='codigocatalogo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('insumo__isnull', True), ('produto__isnull', False)), models.Q(('insumo__isnull', False), ('produto__isnull', True)), _connector='OR'), name='catalogo_codigo_uma_referencia'),
        ),
        migrations.AddConstraint(
            model_name='itemaquisicao',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='compra_item_quantidade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itemaquisicao',
            constraint=models.CheckConstraint(condition=models.Q(('valor_unitario__gte', 0)), name='compra_item_valor_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='itemaquisicao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('insumo__isnull', True), ('produto__isnull', False), ('tipo_item', 'EQUIPAMENTO')), models.Q(('insumo__isnull', False), ('produto__isnull', True), ('tipo_item', 'INSUMO')), _connector='OR'), name='compra_item_referencia_compativel'),
        ),
        migrations.AddConstraint(
            model_name='linharecebimentoremessa',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_recebida__gte', 0)), name='recebimento_qtd_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='linharecebimentoremessa',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_avariada__gte', 0)), name='recebimento_avaria_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='linharecebimentoremessa',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_faltante__gte', 0)), name='recebimento_falta_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='recebimentoremessa',
            constraint=models.UniqueConstraint(fields=('remessa', 'idempotency_key'), name='remessa_recebimento_idempotente'),
        ),
        migrations.AddConstraint(
            model_name='itemremessacompra',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_prevista__gt', 0)), name='remessa_item_previsto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='itemremessacompra',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('equipamento__isnull', True), ('insumo__isnull', False)), models.Q(('equipamento__isnull', False), ('insumo__isnull', True)), _connector='OR'), name='remessa_item_uma_referencia'),
        ),
        migrations.AddConstraint(
            model_name='eventocompra',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('aquisicao__isnull', False), ('remessa__isnull', True)), models.Q(('aquisicao__isnull', True), ('remessa__isnull', False)), _connector='OR'), name='evento_compra_um_agregado'),
        ),
    ]
