# Generated by Django 5.2.6 on 2026-08-20 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_precos_legados(apps, schema_editor):
    Produto = apps.get_model('estoque', 'Produto')
    Equipamento = apps.get_model('estoque', 'Equipamento')
    HistoricoPrecoProduto = apps.get_model('compras', 'HistoricoPrecoProduto')
    mapa_origem = {
        'DOCUMENTO_COMPRA': 'DOCUMENTO_COMPRA',
        'INFORMADO_COMPRAS': 'INFORMADO_COMPRAS',
        'ESTIMATIVA_MERCADO': 'ESTIMATIVA_MERCADO',
        'LEGADO_SEM_DOCUMENTO': 'LEGADO',
        'SEM_PRECO_VALIDADO': 'SEM_PRECO_VALIDADO',
    }
    for produto in Produto.objects.filter(preco_referencia__isnull=True).iterator():
        legado = (
            Equipamento.objects.filter(
                produto_id=produto.pk,
                preco_referencia__isnull=False,
            )
            .order_by('-valor_validado_em', '-data_atualizacao', '-pk')
            .first()
        )
        if not legado:
            continue
        origem = mapa_origem.get(legado.origem_valor, 'LEGADO')
        Produto.objects.filter(pk=produto.pk).update(
            preco_referencia=legado.preco_referencia,
            preco_origem=origem,
            preco_fonte='MIGRAÇÃO DE VALOR LEGADO DE EQUIPAMENTO',
            preco_fornecedor_id=legado.fornecedor_id,
            preco_validado_por_id=legado.valor_validado_por_id,
            preco_validado_em=legado.valor_validado_em,
        )
        if legado.valor_validado_por_id:
            HistoricoPrecoProduto.objects.create(
                produto_id=produto.pk,
                valor_anterior=None,
                valor_novo=legado.preco_referencia,
                origem_anterior='SEM_PRECO_VALIDADO',
                origem_nova=origem,
                fonte='MIGRAÇÃO DE VALOR LEGADO DE EQUIPAMENTO',
                fornecedor_id=legado.fornecedor_id,
                observacao='PREÇO INICIAL PRESERVADO A PARTIR DO HISTÓRICO EXISTENTE.',
                alterado_por_id=legado.valor_validado_por_id,
            )


def reverter_precos_migrados(apps, schema_editor):
    Produto = apps.get_model('estoque', 'Produto')
    HistoricoPrecoProduto = apps.get_model('compras', 'HistoricoPrecoProduto')
    fonte = 'MIGRAÇÃO DE VALOR LEGADO DE EQUIPAMENTO'
    ids = HistoricoPrecoProduto.objects.filter(fonte=fonte).values_list('produto_id', flat=True)
    Produto.objects.filter(pk__in=ids, preco_fonte=fonte).update(
        preco_referencia=None,
        preco_origem='SEM_PRECO_VALIDADO',
        preco_fonte='',
        preco_fornecedor_id=None,
        preco_validado_por_id=None,
        preco_validado_em=None,
    )
    HistoricoPrecoProduto.objects.filter(fonte=fonte).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('estoque', '0039_alter_equipamento_options_alter_perfil_options_and_more'),
        ('insumos', '0032_alter_checklistdiario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPrecoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('valor_novo', models.DecimalField(decimal_places=4, max_digits=14)),
                ('origem_anterior', models.CharField(blank=True, max_length=30)),
                ('origem_nova', models.CharField(max_length=30)),
                ('fonte', models.CharField(blank=True, max_length=255)),
                ('observacao', models.TextField(blank=True)),
                ('alterado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alterado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insumos.fornecedorinsumo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_precos', to='estoque.produto')),
            ],
            options={
                'ordering': ['-alterado_em', '-id'],
                'indexes': [models.Index(fields=['produto', 'alterado_em'], name='compras_his_produto_08c50c_idx')],
            },
        ),
        migrations.RunPython(migrar_precos_legados, reverter_precos_migrados),
    ]
