# Generated by Django 5.2.17 on 2026-09-29 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_catalogoprodutoempresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacidadeCatalogoProdutoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidades', to='compras.catalogoprodutoempresa')),
                ('configurado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacidades_catalogo_configuradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['catalogo__empresa__nome', 'catalogo__produto__descricao', 'codigo'],
                'indexes': [models.Index(fields=['codigo', 'ativa'], name='cap_catalogo_codigo_ativo_idx')],
                'constraints': [models.UniqueConstraint(fields=('catalogo', 'codigo'), name='capacidade_catalogo_codigo_unico')],
            },
        ),
    ]
